<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\Customer;



class PurchaseOrderTransaction
{
		public $additionalTransactionDetail;

		public $author;

		public $availableBalance;

		public $creditLimit;

		public $customerPurchaseOrderAccountId;

		public $externalId;

		public $orderId;

		public $purchaseOrderNumber;

		public $siteId;

		public $tenantId;

		public $transactionAmount;

		public $transactionDate;

		public $transactionDescription;

		public $transactionTypeId;

		public $auditInfo;

}

?>
