<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\CommerceRuntime\Orders;



/**
*	The details associated with a specific item in an order.
*/
class OrderItem
{
	/**
	*The subtotal of the order item including any applied discount calculations.
	*/
	public $discountedTotal;

	/**
	*Estimated amount of discounts applied to the item in the order, which is system-supplied and read-only.
	*/
	public $discountTotal;

	/**
	*Represents the total price of the order item extended to the shopper. This begins with the Unit Price, then uses any of the following prices if they are defined, in the following order: Override Amount, Sale Amount, List Amount.
	*/
	public $extendedTotal;

	/**
	*The total sum of all fees incurred for an item in an order.
	*/
	public $feeTotal;

	/**
	*Code that identifies the location used to fulfill this order item, whether via in-store pickup or direct shipment.
	*/
	public $fulfillmentLocationCode;

	/**
	*The method used to fulfill the item in the order, which is "PickUp" or "Ship". The fulfillment method for the order depends on the supported fulfillment types defined for the product.
	*/
	public $fulfillmentMethod;

		public $handlingAmount;

	/**
	*Unique identifier of a specific item in an order.
	*/
	public $id;

	/**
	*If true, the item in the order can be purchased or fulfilled at regular intervals such as a monthly billing cycle or a digital or physical subscription. This property is reserved for future functionality and is system-supplied and read only.
	*/
	public $isRecurring;

	/**
	*If true, the entity is subject to tax based on the relevant tax rate.
	*/
	public $isTaxable;

	/**
	*The total amount of tax that applied to an item in an order.
	*/
	public $itemTaxTotal;

	/**
	*Language used for the entity. Currently, only "en-US" is supported.
	*/
	public $localeCode;

	/**
	*The unique identifier of the item when it was applied to a cart, prior to checkout, when the cart became an order.
	*/
	public $originalCartItemId;

	/**
	*The quantity of a specific item in an order.
	*/
	public $quantity;

	/**
	*The total amount of sales tax incurred for shipping charges associated with this item in a cart.
	*/
	public $shippingTaxTotal;

	/**
	*Total amount of shipping fees associated with the specified item in the order.
	*/
	public $shippingTotal;

	/**
	*Amount of the item in the order without sales tax, shipping costs, and other fees.
	*/
	public $subtotal;

	/**
	*The amount of the item in the order that is subject to tax. This amount typically represents the order item subtotal before applied discounts.
	*/
	public $taxableTotal;

	/**
	*The total monetary sum of a specific item in an order.
	*/
	public $total;

	/**
	*Identifier and datetime stamp information recorded when a user or application creates, updates, or deletes a resource entity. This value is system-supplied and read-only.
	*/
	public $auditInfo;

	/**
	*The product properties of an item in an order.
	*/
	public $product;

	/**
	*The discount that applies to the product.
	*/
	public $productDiscount;

	/**
	*List of product discounts that apply to the item in the order.
	*/
	public $productDiscounts;

	/**
	*List of shipping discounts that apply to the item in the order.
	*/
	public $shippingDiscounts;

	/**
	*Properties of the unit price associated with the order item.
	*/
	public $unitPrice;

}

?>
