<?php

/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\CommerceRuntime\Orders;



/**
*	The details associated with a specific item in an order.
*/
class OrderItem
{
		public $DiscountedTotal;
	public function getDiscountedTotal() {
		return $this->DiscountedTotal;
	}
	
	public function setDiscountedTotal($discountedTotal) {
		$this->DiscountedTotal = $discountedTotal;
		return $this;
	}

	/**
	*Amount of discounts applied to an item in an order. Usually a negative dollar amount or number. System-supplied and read-only.
	*/
	public $DiscountTotal;
	public function getDiscountTotal() {
		return $this->DiscountTotal;
	}
	
	public function setDiscountTotal($discountTotal) {
		$this->DiscountTotal = $discountTotal;
		return $this;
	}

		public $ExtendedTotal;
	public function getExtendedTotal() {
		return $this->ExtendedTotal;
	}
	
	public function setExtendedTotal($extendedTotal) {
		$this->ExtendedTotal = $extendedTotal;
		return $this;
	}

	/**
	*The total monetary sum of all fees incurred for an item in an order.
	*/
	public $FeeTotal;
	public function getFeeTotal() {
		return $this->FeeTotal;
	}
	
	public function setFeeTotal($feeTotal) {
		$this->FeeTotal = $feeTotal;
		return $this;
	}

	/**
	*Unique identifier of a specific item in an order.
	*/
	public $Id;
	public function getId() {
		return $this->Id;
	}
	
	public function setId($id) {
		$this->Id = $id;
		return $this;
	}

	/**
	*If true, the item in the order can be purchased or fulfilled at regular intervals such as a monthly billing cycle or a digital or physical subscription.
	*/
	public $IsRecurring;
	public function getIsRecurring() {
		return $this->IsRecurring;
	}
	
	public function setIsRecurring($isRecurring) {
		$this->IsRecurring = $isRecurring;
		return $this;
	}

	/**
	*If true, the entity is subject to tax based on the relevant tax rate.
	*/
	public $IsTaxable;
	public function getIsTaxable() {
		return $this->IsTaxable;
	}
	
	public function setIsTaxable($isTaxable) {
		$this->IsTaxable = $isTaxable;
		return $this;
	}

	/**
	*The total amount of tax that applied to an item in an order.
	*/
	public $ItemTaxTotal;
	public function getItemTaxTotal() {
		return $this->ItemTaxTotal;
	}
	
	public function setItemTaxTotal($itemTaxTotal) {
		$this->ItemTaxTotal = $itemTaxTotal;
		return $this;
	}

	/**
	*Language used for the entity. Currently, only "en-US" is supported.
	*/
	public $LocaleCode;
	public function getLocaleCode() {
		return $this->LocaleCode;
	}
	
	public function setLocaleCode($localeCode) {
		$this->LocaleCode = $localeCode;
		return $this;
	}

	/**
	*The unique identifier of the item when it was applied to a cart, prior to checkout, when the cart became an order.
	*/
	public $OriginalCartItemId;
	public function getOriginalCartItemId() {
		return $this->OriginalCartItemId;
	}
	
	public function setOriginalCartItemId($originalCartItemId) {
		$this->OriginalCartItemId = $originalCartItemId;
		return $this;
	}

	/**
	*The unique identifier of the product reservation for the item in an order.
	*/
	public $ProductReservationId;
	public function getProductReservationId() {
		return $this->ProductReservationId;
	}
	
	public function setProductReservationId($productReservationId) {
		$this->ProductReservationId = $productReservationId;
		return $this;
	}

	/**
	*The quantity of a specific item in an order.
	*/
	public $Quantity;
	public function getQuantity() {
		return $this->Quantity;
	}
	
	public function setQuantity($quantity) {
		$this->Quantity = $quantity;
		return $this;
	}

	/**
	*The total amount of sales tax incurred for shipping charges associated with this item in a cart.
	*/
	public $ShippingTaxTotal;
	public function getShippingTaxTotal() {
		return $this->ShippingTaxTotal;
	}
	
	public function setShippingTaxTotal($shippingTaxTotal) {
		$this->ShippingTaxTotal = $shippingTaxTotal;
		return $this;
	}

	/**
	*Total amount of shipping fees associated with the specified item in the order.
	*/
	public $ShippingTotal;
	public function getShippingTotal() {
		return $this->ShippingTotal;
	}
	
	public function setShippingTotal($shippingTotal) {
		$this->ShippingTotal = $shippingTotal;
		return $this;
	}

	/**
	*Amount of the item in the order without sales tax, shipping costs, and other fees.
	*/
	public $Subtotal;
	public function getSubtotal() {
		return $this->Subtotal;
	}
	
	public function setSubtotal($subtotal) {
		$this->Subtotal = $subtotal;
		return $this;
	}

	/**
	*The amount of the item in the order that is subject to tax. This amount typically represents the order item subtotal before applied discounts.
	*/
	public $TaxableTotal;
	public function getTaxableTotal() {
		return $this->TaxableTotal;
	}
	
	public function setTaxableTotal($taxableTotal) {
		$this->TaxableTotal = $taxableTotal;
		return $this;
	}

	/**
	*The total monetary sum of a specific item in an order.
	*/
	public $Total;
	public function getTotal() {
		return $this->Total;
	}
	
	public function setTotal($total) {
		$this->Total = $total;
		return $this;
	}

	/**
	*Identifier and datetime stamp information recorded when creating or updating a resource entity. This value is system-supplied and read-only.
	*/
	public $AuditInfo;
	public function getAuditInfo() {
		return $this->AuditInfo;
	}
	
	public function setAuditInfo($auditInfo) {
		$this->AuditInfo = $auditInfo;
		return $this;
	}

	/**
	*The product properties of an item in an order.
	*/
	public $Product;
	public function getProduct() {
		return $this->Product;
	}
	
	public function setProduct($product) {
		$this->Product = $product;
		return $this;
	}

	/**
	*List of product discounts that apply to the item in the order.
	*/
	public $ProductDiscounts;
	public function getProductDiscounts() {
		return $this->ProductDiscounts;
	}
	
	public function setProductDiscounts($productDiscounts) {
		$this->ProductDiscounts = $productDiscounts;
		return $this;
	}

	/**
	*List of shipping discounts that apply to the item in the order.
	*/
	public $ShippingDiscounts;
	public function getShippingDiscounts() {
		return $this->ShippingDiscounts;
	}
	
	public function setShippingDiscounts($shippingDiscounts) {
		$this->ShippingDiscounts = $shippingDiscounts;
		return $this;
	}

	/**
	*Properties of the unit price associated with the order item.
	*/
	public $UnitPrice;
	public function getUnitPrice() {
		return $this->UnitPrice;
	}
	
	public function setUnitPrice($unitPrice) {
		$this->UnitPrice = $unitPrice;
		return $this;
	}

}

?>
