<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\Reference;



/**
*	Properties to describe the unit of measure.
*/
class UnitOfMeasure
{
		public $name;

		public $pluralName;

		public $symbol;

		public $unitOfMeasureType;

}

?>
