<?php

/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\Content;



/**
*	A type of content property value.
*/
class PropertyValueType
{
	/**
	*The name of the property type value.
	*/
	public $name;
	public function getName() {
		return $this->name;
	}
	
	public function setName($name) {
		$this->name = $name;
		return $this;
	}

	/**
	*The data storage type associated with this property type value.
	*/
	public $storageType;
	public function getStorageType() {
		return $this->storageType;
	}
	
	public function setStorageType($storageType) {
		$this->storageType = $storageType;
		return $this;
	}

}

?>
