<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Urls\Commerce\Catalog\Admin;

use Mozu\Api\MozuUrl;
use Mozu\Api\UrlLocation;

class DiscountUrl  {

	/**
		* Get Resource Url for GetDiscounts
		* @param string $filter 
		* @param int $pageSize 
		* @param string $responseFields 
		* @param string $sortBy 
		* @param int $startIndex 
		* @return string Resource Url
	*/
	public static function getDiscountsUrl($filter, $pageSize, $responseFields, $sortBy, $startIndex)
	{
		$url = "/api/commerce/catalog/admin/discounts/?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&responseFields={responseFields}";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"GET", false) ;
		$url = $mozuUrl->formatUrl("filter", $filter);
		$url = $mozuUrl->formatUrl("pageSize", $pageSize);
		$url = $mozuUrl->formatUrl("responseFields", $responseFields);
		$url = $mozuUrl->formatUrl("sortBy", $sortBy);
		$url = $mozuUrl->formatUrl("startIndex", $startIndex);
		return $mozuUrl;
	}
	
	/**
		* Get Resource Url for GetDiscountContent
		* @param int $discountId Unique identifier of the discount. System-supplied and read-only.
		* @param string $responseFields 
		* @return string Resource Url
	*/
	public static function getDiscountContentUrl($discountId, $responseFields)
	{
		$url = "/api/commerce/catalog/admin/discounts/{discountId}/content?responseFields={responseFields}";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"GET", false) ;
		$url = $mozuUrl->formatUrl("discountId", $discountId);
		$url = $mozuUrl->formatUrl("responseFields", $responseFields);
		return $mozuUrl;
	}
	
	/**
		* Get Resource Url for GetDiscount
		* @param int $discountId Unique identifier of the discount. System-supplied and read-only.
		* @param string $responseFields 
		* @return string Resource Url
	*/
	public static function getDiscountUrl($discountId, $responseFields)
	{
		$url = "/api/commerce/catalog/admin/discounts/{discountId}?responseFields={responseFields}";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"GET", false) ;
		$url = $mozuUrl->formatUrl("discountId", $discountId);
		$url = $mozuUrl->formatUrl("responseFields", $responseFields);
		return $mozuUrl;
	}
	
	/**
		* Get Resource Url for GenerateRandomCoupon
		* @param string $responseFields 
		* @return string Resource Url
	*/
	public static function generateRandomCouponUrl($responseFields)
	{
		$url = "/api/commerce/catalog/admin/discounts/generate-random-coupon?responseFields={responseFields}";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"GET", false) ;
		$url = $mozuUrl->formatUrl("responseFields", $responseFields);
		return $mozuUrl;
	}
	
	/**
		* Get Resource Url for CreateDiscount
		* @param string $responseFields 
		* @return string Resource Url
	*/
	public static function createDiscountUrl($responseFields)
	{
		$url = "/api/commerce/catalog/admin/discounts/?responseFields={responseFields}";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"POST", false) ;
		$url = $mozuUrl->formatUrl("responseFields", $responseFields);
		return $mozuUrl;
	}
	
	/**
		* Get Resource Url for UpdateDiscountContent
		* @param int $discountId Unique identifier of the discount. System-supplied and read-only.
		* @param string $responseFields 
		* @return string Resource Url
	*/
	public static function updateDiscountContentUrl($discountId, $responseFields)
	{
		$url = "/api/commerce/catalog/admin/discounts/{discountId}/content?responseFields={responseFields}";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"PUT", false) ;
		$url = $mozuUrl->formatUrl("discountId", $discountId);
		$url = $mozuUrl->formatUrl("responseFields", $responseFields);
		return $mozuUrl;
	}
	
	/**
		* Get Resource Url for UpdateDiscount
		* @param int $discountId Unique identifier of the discount to update.
		* @param string $responseFields 
		* @return string Resource Url
	*/
	public static function updateDiscountUrl($discountId, $responseFields)
	{
		$url = "/api/commerce/catalog/admin/discounts/{discountId}?responseFields={responseFields}";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"PUT", false) ;
		$url = $mozuUrl->formatUrl("discountId", $discountId);
		$url = $mozuUrl->formatUrl("responseFields", $responseFields);
		return $mozuUrl;
	}
	
	/**
		* Get Resource Url for DeleteDiscount
		* @param int $discountId Unique identifier of the discount. System-supplied and read-only.
		* @return string Resource Url
	*/
	public static function deleteDiscountUrl($discountId)
	{
		$url = "/api/commerce/catalog/admin/discounts/{discountId}";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"DELETE", false) ;
		$url = $mozuUrl->formatUrl("discountId", $discountId);
		return $mozuUrl;
	}
	
}

?>

