<?php


/**
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

namespace Mozu\Api\Clients\Commerce\Orders;

use Mozu\Api\MozuClient;
use Mozu\Api\Urls\Commerce\Orders\ShipmentUrl;

/**
* 
*/
class ShipmentClient {

	/**
	* 
	*
	* @param string $orderId 
	* @param string $shipmentId 
	* @return MozuClient
	*/
	public static function getShipmentClient( $orderId,  $shipmentId, Mozu\Api\Security\AuthTicket &$authTicket= null)
	{
		$url = ShipmentUrl::getShipmentUrl($orderId, $shipmentId);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url);
		if ($authTicket != null)
			$mozuClient = $mozuClient->withUserAuth($authTicket);
		return $mozuClient;

	}
	
	/**
	* 
	*
	* @param string $orderId 
	* @return MozuClient
	*/
	public static function getAvailableShipmentMethodsClient( $orderId, Mozu\Api\Security\AuthTicket &$authTicket= null)
	{
		$url = ShipmentUrl::getAvailableShipmentMethodsUrl($orderId);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url);
		if ($authTicket != null)
			$mozuClient = $mozuClient->withUserAuth($authTicket);
		return $mozuClient;

	}
	
	/**
	* 
	*
	* @param string $orderId 
	* @param array|string $packageIds 
	* @return MozuClient
	*/
	public static function createPackageShipmentsClient($packageIds,  $orderId, Mozu\Api\Security\AuthTicket &$authTicket= null)
	{
		$url = ShipmentUrl::createPackageShipmentsUrl($orderId);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url)->withBody($packageIds);
		if ($authTicket != null)
			$mozuClient = $mozuClient->withUserAuth($authTicket);
		return $mozuClient;

	}
	
	/**
	* 
	*
	* @param string $orderId 
	* @param string $shipmentId 
	*/
	public static function deleteShipmentClient( $orderId,  $shipmentId, Mozu\Api\Security\AuthTicket &$authTicket= null)
	{
		$url = ShipmentUrl::deleteShipmentUrl($orderId, $shipmentId);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url);
		if ($authTicket != null)
			$mozuClient = $mozuClient->withUserAuth($authTicket);
		return $mozuClient;

	}
	
	
}

?>

