<?php

/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Urls\Commerce\Settings\Shipping;

use Mozu\Api\MozuUrl;
use Mozu\Api\UrlLocation;

class SiteShippingHandlingFeeUrl  {

	/**
		* Get Resource Url for GetOrderHandlingFee
		* @return string Resource Url
	*/
	public static function getOrderHandlingFeeUrl()
	{
		$url = "/api/commerce/settings/shipping/orderhandlingfee";
		return new MozuUrl($url, UrlLocation::TENANT_POD,"GET") ;
	}
	
	/**
		* Get Resource Url for CreateOrderHandlingFee
		* @return string Resource Url
	*/
	public static function createOrderHandlingFeeUrl()
	{
		$url = "/api/commerce/settings/shipping/orderhandlingfee";
		return new MozuUrl($url, UrlLocation::TENANT_POD,"POST") ;
	}
	
	/**
		* Get Resource Url for UpdateOrderHandlingFee
		* @return string Resource Url
	*/
	public static function updateOrderHandlingFeeUrl()
	{
		$url = "/api/commerce/settings/shipping/orderhandlingfee";
		return new MozuUrl($url, UrlLocation::TENANT_POD,"PUT") ;
	}
	
}

?>

