<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\PaymentService;



/**
*	Properties of the credential fields associated with the payment gateway.
*/
class GatewayCredentialFieldDefinition
{
		public $adminDisplayOrder;

		public $displayName;

		public $isPublic;

		public $name;

}

?>
