<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\ShippingRuntime;



/**
*	Properties required to request a shipping rate calculation.
*/
class RateRequest
{
	/**
	*List of shipping carriers for which to retrieve shipping rate information.
	*/
	public $carrierIds;

	/**
	*The estimated date and time the shipment will be shipped to the shopper. This calculation is based on product stock, availability, date of order entry, and location.
	*/
	public $estimatedShipmentDate;

	/**
	*If true, the destination address associated with the shipping rate request is a commercial address.
	*/
	public $isDestinationAddressCommercial;

	/**
	*3-letter ISO 4217 standard global currency code. Currently, only "USD" (US Dollar) is supported.
	*/
	public $isoCurrencyCode;

	/**
	*The Order SubTotal After Discounts to be used in rate calculation
	*/
	public $orderDiscountedSubTotal;

	/**
	*The total monetary amount of the order. This amount is used to calculate the shipping rate estimate.
	*/
	public $orderTotal;

	/**
	*The Order ID to be used in rate calculation Information al only
	*/
	public $relatedOrderId;

	/**
	*The shipping methods associated with this request.
	*/
	public $shippingServiceTypes;

	/**
	*Collection of carrier-specific key-value attribute pairs associated with a shipping carrier. These are required to retrieve a shipping rate request and are returned for the generated shipping label.
	*/
	public $customAttributes;

	/**
	*Mozu.ShippingRuntime.Contracts.RateRequest data ApiTypeMember DOCUMENT_HERE 
	*/
	public $data;

	/**
	*The physical address orders are sent to as a shipping destination. This address may contain multiple lines, city, state/province, country, and zip/postal code. The destination is used to calculate shipping costs.
	*/
	public $destinationAddress;

	/**
	*Collection list of items. All returned data is provided in an items array. For a failed request, the returned response may be success with an empty item collection. Items are used throughout APIs for carts, wish lists, documents, payments, returns, properties, and more.
	*/
	public $items;

	/**
	*The physical address from which the order or shipment will ship.
	*/
	public $originAddress;

}

?>
