<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\CommerceRuntime\Commerce;



class ThresholdMessage
{
		public $discountId;

		public $message;

		public $requiresCouponCode;

		public $showInCart;

		public $showOnCheckout;

		public $thresholdValue;

}

?>
