<?php

/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\PricingRuntime;



/**
*	Details of a property defined for a product.
*/
class ProductProperty
{
	/**
	*The fully qualified name of the attribute, which is a user defined attribute identifier.
	*/
	public $attributeFQN;

	/**
	*If true, this product property does not appear on the storefront.
	*/
	public $isHidden;

	/**
	*If true, the product property has multiple values.
	*/
	public $isMultiValue;

	/**
	*Details of a product attribute.
	*/
	public $attributeDetail;

	/**
	*List of values predefined for the product property attribute.
	*/
	public $values;

}

?>
