<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\SiteSettings\Order;



/**
*	Mozu.SiteSettings.Order.Contracts.PurchaseOrderPaymentDefinition ApiType DOCUMENT_HERE 
*/
class PurchaseOrderPaymentDefinition
{
	/**
	*Indicates whether another payment can be used with the purchase order
	*/
	public $allowSplitPayment;

	/**
	*Indicates if the object or process is enabled. This indicator is used on external payment workflows and product option values. For product options, if true, the product option value is available for a shopper to choose. During configuration, this property will be false if the option value is invalid with other selected options. For external payment workflows, if true, the workflow is enabled and available for routing payments for the submitted order.
	*/
	public $isEnabled;

	/**
	*Mozu.SiteSettings.Order.Contracts.PurchaseOrderPaymentDefinition customFields ApiTypeMember DOCUMENT_HERE 
	*/
	public $customFields;

	/**
	*Allowed net terms
	*/
	public $paymentTerms;

}

?>
