<?php


/**
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

namespace Mozu\Api\Clients\Content\Documentlists;

use Mozu\Api\MozuClient;
use Mozu\Api\Urls\Content\Documentlists\FacetUrl;

/**
* Use the facets subresource to allow a merchant to add information for product indexing and searching.
*/
class FacetClient {

	/**
	* Retrieves the properties of facets that aid in indexing and searching.
	*
	* @param string $documentListName The document list associated with the facets to retrieve.
	* @param string $propertyName The property name associated with the facets to retrieve.
	* @param string $publishState The current state of the document, which is Active, Draft, or Latest. Active documents are published and cannot be deleted. Querying Latest returns the most recent version of the document, regardless of whether it is published or a draft.
	* @return MozuClient
	*/
	public static function getFacetsClient($documentListName, $propertyName, $publishState)
	{
		$url = FacetUrl::getFacetsUrl($documentListName, $propertyName, $publishState);
		$verb = "GET";
		$mozuClient = new MozuClient();
		$mozuClient->withVerb($verb)
				->withResourceUrl($url);
		return $mozuClient;

	}
	
	
}

?>

