<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\ProductAdmin;



/**
*	Item used to define additional key-value pairs of data associated with a product attribute.
*/
class AttributeMetadataItem
{
		public $key;

		public $value;

}

?>
