<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\ProductAdmin;



/**
*	Properties of the conditions that must be met for a discount to apply to an order.
*/
class DiscountCondition
{
	/**
	*Code of a discount coupon. This code can be used by a shopper when a coupon code is required to earn the associated discount on a purchase.
	*/
	public $couponCode;

	/**
	*Date and time in UTC format when a discount, credit, wish list, or cart expires. An expired discount no longer can be redeemed. An expired wish list is no longer available. An expired credit can no longer be redeemed for a purchase. Acart becomes inactive and expired based on a system-calculated interval. For example, if an anonymous shopper has 14 days of inactivity, the cart is considered abandoned after that period of inactivity. System-supplied and read-only.
	*/
	public $expirationDate;

	/**
	*List of payment types that trigger this discount to be valid.
	*/
	public $includedPaymentWorkflows;

	/**
	*The maximum number of times the discount can be redeemed.
	*/
	public $maxRedemptionCount;

	/**
	*This pecifies the minimum amount that must be purchased in the combined categories defined in IncludedCategories. This amount is calculated before discounting and it is not used if IncludedCategories is empty.
	*/
	public $minimumCategorySubtotalBeforeDiscounts;

	/**
	*The minimum customer lifetime value amount required to redeem this discount.
	*/
	public $minimumLifetimeValueAmount;

	/**
	*The minimum order amount required to redeem this discount.
	*/
	public $minimumOrderAmount;

	/**
	*This specifies the minimum quantity of products in the categories specified in IncludedCategories, which must be purchased to qualify for the associated discount. This defaults to 1 if  null, and IncludedCategories has values.
	*/
	public $minimumQuantityProductsRequiredInCategories;

	/**
	*This specifies the minimum quantity of products in the specified IncludedProducts that must be purchased to qualify for the associated discount. This defaults to 1 if  null, and IncludedProducts has values.
	*/
	public $minimumQuantityRequiredProducts;

	/**
	*If true, only authenticated users can redeem the discount. If false, anonymous users can redeem the discount.
	*/
	public $requiresAuthenticatedUser;

	/**
	*If true, redemption of this discount requires entry of a coupon code.
	*/
	public $requiresCoupon;

	/**
	*The earliest date and time this discount can be redeemed.
	*/
	public $startDate;

	/**
	*List of customer segments associated with the discount. Shoppers who are members of an associated customer segment can redeem this discount.
	*/
	public $customerSegments;

	/**
	*List of the product categories that are not eligible for the discount.
	*/
	public $excludedCategories;

	/**
	*List of products that are not eligible for the discount.
	*/
	public $excludedProducts;

	/**
	*List of product categories that are eligible for the discount.
	*/
	public $includedCategories;

	/**
	*List of products that are eligible for the discount.
	*/
	public $includedProducts;

}

?>
