<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\ProductAdmin;



/**
*	Properties of the category, price, or attribute facet shoppers use to filter product display results on a storefront.
*/
class Facet
{
		public $categoryId;

		public $facetId;

		public $facetType;

		public $isHidden;

		public $order;

		public $overrideFacetId;

		public $valueSortType;

		public $auditInfo;

		public $rangeQueries;

		public $source;

		public $validity;

}

?>
