<?php


/**
* <auto-generated>
*     This code was generated by Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

namespace Mozu\Api\Resources\Commerce\Checkouts;

use Mozu\Api\Clients\Commerce\Checkouts\PaymentClient;
use Mozu\Api\ApiContext;


/**
* 
*/
class PaymentResource {

		private $apiContext;
			
	public function __construct(ApiContext $apiContext) 
	{
		$this->apiContext = $apiContext;
	}

	



	/**
	* 
	*
	* @param string $checkoutId 
	* @param string $paymentId 
	* @param string $responseFields 
	* @param PaymentAction $action 
	* @return Checkout 
	* @deprecated deprecated since version 1.17
	*/
	public function performPaymentAction($action, $checkoutId, $paymentId, $responseFields =  null)
	{
		$mozuClient = PaymentClient::performPaymentActionClient($action, $checkoutId, $paymentId, $responseFields);
		$mozuClient = $mozuClient->withContext($this->apiContext);
		$mozuClient->execute();
		return $mozuClient->getResult();

	}
	
/**
	* 
	*
	* @param string $checkoutId 
	* @param string $paymentId 
	* @param string $responseFields 
	* @return Promise - use $promise->then(sucessfn, errorfn). successFn is passed Mozu\Api\MozuResult. errorFn is passed Mozu\Api\ApiException
	*/
	public function performPaymentActionAsync($action, $checkoutId, $paymentId, $responseFields =  null)
	{
		$mozuClient = PaymentClient::performPaymentActionClient($action, $checkoutId, $paymentId, $responseFields);
		$mozuClient = $mozuClient->withContext($this->apiContext);
		return $mozuClient->executeAsync();

	}
	
	/**
	* 
	*
	* @param string $checkoutId 
	* @param string $responseFields 
	* @param PaymentAction $action 
	* @return Checkout 
	* @deprecated deprecated since version 1.17
	*/
	public function createPaymentAction($action, $checkoutId, $responseFields =  null)
	{
		$mozuClient = PaymentClient::createPaymentActionClient($action, $checkoutId, $responseFields);
		$mozuClient = $mozuClient->withContext($this->apiContext);
		$mozuClient->execute();
		return $mozuClient->getResult();

	}
	
/**
	* 
	*
	* @param string $checkoutId 
	* @param string $responseFields 
	* @return Promise - use $promise->then(sucessfn, errorfn). successFn is passed Mozu\Api\MozuResult. errorFn is passed Mozu\Api\ApiException
	*/
	public function createPaymentActionAsync($action, $checkoutId, $responseFields =  null)
	{
		$mozuClient = PaymentClient::createPaymentActionClient($action, $checkoutId, $responseFields);
		$mozuClient = $mozuClient->withContext($this->apiContext);
		return $mozuClient->executeAsync();

	}
	
	
}

?>

