<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Urls\Commerce\Catalog\Admin\Discounts;

use Mozu\Api\MozuUrl;
use Mozu\Api\UrlLocation;

class DiscountTargetUrl  {

	/**
		* Get Resource Url for GetDiscountTarget
		* @param int $discountId discountId parameter description DOCUMENT_HERE 
		* @param string $responseFields Use this field to include those fields which are not included by default.
		* @return string Resource Url
	*/
	public static function getDiscountTargetUrl($discountId, $responseFields)
	{
		$url = "/api/commerce/catalog/admin/discounts/{discountId}/target?responseFields={responseFields}";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"GET", false) ;
		$url = $mozuUrl->formatUrl("discountId", $discountId);
		$url = $mozuUrl->formatUrl("responseFields", $responseFields);
		return $mozuUrl;
	}
	
	/**
		* Get Resource Url for UpdateDiscountTarget
		* @param int $discountId discountId parameter description DOCUMENT_HERE 
		* @param string $responseFields Use this field to include those fields which are not included by default.
		* @return string Resource Url
	*/
	public static function updateDiscountTargetUrl($discountId, $responseFields)
	{
		$url = "/api/commerce/catalog/admin/discounts/{discountId}/target?responseFields={responseFields}";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"PUT", false) ;
		$url = $mozuUrl->formatUrl("discountId", $discountId);
		$url = $mozuUrl->formatUrl("responseFields", $responseFields);
		return $mozuUrl;
	}
	
}

?>

