<?php


/**
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

namespace Mozu\Api\Resources\Commerce\Settings\Checkout;

use Mozu\Api\MozuClient;
use Mozu\Api\Clients\Commerce\Settings\Checkout\CustomerCheckoutSettingsClient;
use Mozu\Api\ApiContext;

/**
* 
*/
class CustomerCheckoutSettingsResource {

	private $apiContext;
	public function __construct(ApiContext $apiContext) 
	{
		$this->apiContext = $apiContext;
	}

	/**
	* 
	*
	* @return CustomerCheckoutSettings 
	*/
	public function getCustomerCheckoutSettings(Mozu\Api\Security\AuthTicket &$authTicket= null)
	{
		$mozuClient = CustomerCheckoutSettingsClient::getCustomerCheckoutSettingsClient($authTicket);
		$mozuClient = $mozuClient->withContext($this->apiContext);
		$mozuClient->execute();
		return $mozuClient->getResult();

	}
	
	/**
	* 
	*
	* @param CustomerCheckoutSettings $customerCheckoutSettings 
	* @return CustomerCheckoutSettings 
	*/
	public function updateCustomerCheckoutSettings($customerCheckoutSettings, Mozu\Api\Security\AuthTicket &$authTicket= null)
	{
		$mozuClient = CustomerCheckoutSettingsClient::updateCustomerCheckoutSettingsClient($customerCheckoutSettings, $authTicket);
		$mozuClient = $mozuClient->withContext($this->apiContext);
		$mozuClient->execute();
		return $mozuClient->getResult();

	}
	
	
}

?>

