<?php

/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\Location;



class RegularHours
{
		public $friday;
	public function getFriday() {
		return $this->friday;
	}
	
	public function setFriday($friday) {
		$this->friday = $friday;
		return $this;
	}

		public $monday;
	public function getMonday() {
		return $this->monday;
	}
	
	public function setMonday($monday) {
		$this->monday = $monday;
		return $this;
	}

		public $saturday;
	public function getSaturday() {
		return $this->saturday;
	}
	
	public function setSaturday($saturday) {
		$this->saturday = $saturday;
		return $this;
	}

		public $sunday;
	public function getSunday() {
		return $this->sunday;
	}
	
	public function setSunday($sunday) {
		$this->sunday = $sunday;
		return $this;
	}

		public $thursday;
	public function getThursday() {
		return $this->thursday;
	}
	
	public function setThursday($thursday) {
		$this->thursday = $thursday;
		return $this;
	}

		public $tuesday;
	public function getTuesday() {
		return $this->tuesday;
	}
	
	public function setTuesday($tuesday) {
		$this->tuesday = $tuesday;
		return $this;
	}

		public $wednesday;
	public function getWednesday() {
		return $this->wednesday;
	}
	
	public function setWednesday($wednesday) {
		$this->wednesday = $wednesday;
		return $this;
	}

}

?>
