<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\Customer;



/**
*	Contact information, including the contact's name, address, phone numbers, email addresses, and company (if supplied). Also indicates whether this is a billing, shipping, or billing and shipping contact.
*/
class CustomerContact
{
	/**
	*Unique identifier of the customer account generated by the system. Account IDs are generated at account creation.
	*/
	public $accountId;

	/**
	*The legal or doing business as (DBA) or tradestyle name of the business or organization. The maximum character length is 200.
	*/
	public $companyOrOrganization;

	/**
	*The email address of the specified user or the email address associated with the specified entity.
	*/
	public $email;

	/**
	*The fax number associated with the customer account.
	*/
	public $faxNumber;

	/**
	*The first name of the contact. The maximum character length is 200.
	*/
	public $firstName;

	/**
	*Unique identifier of the source product property. For a product field it will be the name of the field. For a product attribute it will be the Attribute FQN. 
	*/
	public $id;

	/**
	*Descriptive text used as a label for objects, such as field names, facets, date ranges, contact information, and package information.
	*/
	public $label;

	/**
	*The last name or surname of the contact. The maximum character length is 200.
	*/
	public $lastNameOrSurname;

	/**
	*The middle name or the first initial of the middle name of the contact. The maximum character length is 100.
	*/
	public $middleNameOrInitial;

	/**
	*All address information for the contact. This data is used to validate the address for the customer account and includes the full address.
	*/
	public $address;

	/**
	*Identifier and datetime stamp information recorded when a user or application creates, updates, or deletes a resource entity. This value is system-supplied and read-only.
	*/
	public $auditInfo;

	/**
	*List of phone numbers associated with the customer account contact. The phone numbers include area codes.
	*/
	public $phoneNumbers;

	/**
	*List of the types associated with a customer contact, such as Billing or Fulfillment.
	*/
	public $types;

}

?>
