<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\Customer;



/**
*	The information required to modify a shopper account password.
*/
class PasswordInfo
{
	/**
	*The External Password, typically used for imports in conjunction with a custom action
	*/
	public $externalPassword;

	/**
	*The new password entered and saved by the user of the account. 
	*/
	public $newPassword;

	/**
	*The previous shopper account password value.
	*/
	public $oldPassword;

}

?>
