<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\AppDev;



/**
*	Mozu.AppDev.Contracts.ApplicationSummary ApiType DOCUMENT_HERE 
*/
class ApplicationSummary
{
	/**
	*Unique identifier of an app available in your Mozu tenant or within Mozu Dev Center. This ID is unique across all apps installed, initialized, and enabled in the Mozu Admin and those in development through the Dev Center Console.
	*/
	public $appId;

	/**
	*The AppKey is a runtime type.
	*/
	public $appKey;

	/**
	*Mozu.AppDev.Contracts.ApplicationSummary applicationId ApiTypeMember DOCUMENT_HERE 
	*/
	public $applicationId;

	/**
	*Mozu.AppDev.Contracts.ApplicationSummary applicationNamespace ApiTypeMember DOCUMENT_HERE 
	*/
	public $applicationNamespace;

	/**
	*Mozu.AppDev.Contracts.ApplicationSummary applicationStatusId ApiTypeMember DOCUMENT_HERE 
	*/
	public $applicationStatusId;

	/**
	*Mozu.AppDev.Contracts.ApplicationSummary applicationStatusName ApiTypeMember DOCUMENT_HERE 
	*/
	public $applicationStatusName;

	/**
	*Mozu.AppDev.Contracts.ApplicationSummary applicationTypeId ApiTypeMember DOCUMENT_HERE 
	*/
	public $applicationTypeId;

	/**
	*Mozu.AppDev.Contracts.ApplicationSummary appSchemeVersion ApiTypeMember DOCUMENT_HERE 
	*/
	public $appSchemeVersion;

	/**
	*Mozu.AppDev.Contracts.ApplicationSummary hasVersions ApiTypeMember DOCUMENT_HERE 
	*/
	public $hasVersions;

	/**
	*The display name of the source product property. For a product field it will be the display name of the field. For a product attribute it will be the Attribute Name.
	*/
	public $name;

	/**
	*The AppKey is a runtime type. This only applies for themes that inherit from another theme.
	*/
	public $parentAppKey;

	/**
	*Mozu.AppDev.Contracts.ApplicationSummary parentName ApiTypeMember DOCUMENT_HERE 
	*/
	public $parentName;

	/**
	*Mozu.AppDev.Contracts.ApplicationSummary releasePackageId ApiTypeMember DOCUMENT_HERE 
	*/
	public $releasePackageId;

	/**
	*Mozu.AppDev.Contracts.ApplicationSummary releasePackageName ApiTypeMember DOCUMENT_HERE 
	*/
	public $releasePackageName;

	/**
	*Mozu.AppDev.Contracts.ApplicationSummary updateAvailable ApiTypeMember DOCUMENT_HERE 
	*/
	public $updateAvailable;

	/**
	*The AppKey is a runtime type. This only applies for themes that inherit from another theme. It shows the most current update available.
	*/
	public $updateParentAppKey;

	/**
	*Mozu.AppDev.Contracts.ApplicationSummary applicationVersion ApiTypeMember DOCUMENT_HERE 
	*/
	public $applicationVersion;

}

?>
