<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\AppDev;



/**
*	Mozu.AppDev.Contracts.AppVersion ApiType DOCUMENT_HERE 
*/
class AppVersion
{
	/**
	*Mozu.AppDev.Contracts.AppVersion majorVersion ApiTypeMember DOCUMENT_HERE 
	*/
	public $majorVersion;

	/**
	*Mozu.AppDev.Contracts.AppVersion minorVersion ApiTypeMember DOCUMENT_HERE 
	*/
	public $minorVersion;

	/**
	*Mozu.AppDev.Contracts.AppVersion revision ApiTypeMember DOCUMENT_HERE 
	*/
	public $revision;

}

?>
