<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\Tenant;



/**
*	Properties of an individual product catalog.
*/
class Catalog
{
		public $createDate;

		public $defaultCurrencyCode;

		public $defaultLocaleCode;

		public $deleteDate;

		public $id;

		public $isDeleted;

		public $masterCatalogId;

		public $name;

	/**
	*The current status of the product catalog.
	*/
	public $status;

	/**
	*Unique identifier of the Mozu tenant.
	*/
	public $tenantId;

		public $updateDate;

}

?>
