<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\Tenant;



/**
*	Properties of a master product catalog defined for a tenant. All catalogs and sites associated with a master catalog share product definitions.
*/
class MasterCatalog
{
		public $createDate;

		public $defaultCurrencyCode;

		public $defaultLocaleCode;

		public $deleteDate;

		public $id;

		public $isDeleted;

		public $name;

	/**
	*The current status of the master catalog.
	*/
	public $status;

	/**
	*Unique identifier of the Mozu tenant.
	*/
	public $tenantId;

		public $updateDate;

		public $catalogs;

}

?>
