<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\CommerceRuntime\Fulfillment;



/**
*	Properties of an item shipped in a physical package.
*/
class PackageItem
{
	/**
	*This specifies the type of fulfillment item.
	*/
	public $fulfillmentItemType;

	/**
	*Merchant-created code that uniquely identifies the product such as a SKU or item number. Once created, the product code is read-only.
	*/
	public $productCode;

	/**
	*The quantity of an item shipped in the specified package.
	*/
	public $quantity;

}

?>
