<?php


/**
* <auto-generated>
*     This code was generated by Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

namespace Mozu\Api\Resources\Commerce\Payments;

use Mozu\Api\Clients\Commerce\Payments\PublicTokenClient;
use Mozu\Api\ApiContext;


/**
* 
*/
class PublicTokenResource {

		private $apiContext;
			
	public function __construct(ApiContext $apiContext) 
	{
		$this->apiContext = $apiContext;
	}

	



	/**
	* 
	*
	* @param string $responseFields 
	* @param PublicToken $request 
	* @return TokenResponse 
	* @deprecated deprecated since version 1.17
	*/
	public function create($request, $responseFields =  null)
	{
		$mozuClient = PublicTokenClient::createClient($request, $responseFields);
		$mozuClient = $mozuClient->withContext($this->apiContext);
		$mozuClient->execute();
		return $mozuClient->getResult();

	}
	
/**
	* 
	*
	* @param string $responseFields 
	* @return Promise - use $promise->then(sucessfn, errorfn). successFn is passed Mozu\Api\MozuResult. errorFn is passed Mozu\Api\ApiException
	*/
	public function createAsync($request, $responseFields =  null)
	{
		$mozuClient = PublicTokenClient::createClient($request, $responseFields);
		$mozuClient = $mozuClient->withContext($this->apiContext);
		return $mozuClient->executeAsync();

	}
	
	/**
	* 
	*
	* @param string $cardType 
	* @param string $responseFields 
	* @param ExecuteRequest $request 
	* @return JObject 
	* @deprecated deprecated since version 1.17
	*/
	public function execute($request, $cardType, $responseFields =  null)
	{
		$mozuClient = PublicTokenClient::executeClient($request, $cardType, $responseFields);
		$mozuClient = $mozuClient->withContext($this->apiContext);
		$mozuClient->execute();
		return $mozuClient->getResult();

	}
	
/**
	* 
	*
	* @param string $cardType 
	* @param string $responseFields 
	* @return Promise - use $promise->then(sucessfn, errorfn). successFn is passed Mozu\Api\MozuResult. errorFn is passed Mozu\Api\ApiException
	*/
	public function executeAsync($request, $cardType, $responseFields =  null)
	{
		$mozuClient = PublicTokenClient::executeClient($request, $cardType, $responseFields);
		$mozuClient = $mozuClient->withContext($this->apiContext);
		return $mozuClient->executeAsync();

	}
	
	
}

?>

