<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Urls\Commerce\Checkouts;

use Mozu\Api\MozuUrl;
use Mozu\Api\UrlLocation;

class OrderItemUrl  {

	/**
		* Get Resource Url for SplitItem
		* @param string $checkoutId 
		* @param string $itemId 
		* @param int $quantity 
		* @param string $responseFields 
		* @return string Resource Url
	*/
	public static function splitItemUrl($checkoutId, $itemId, $quantity, $responseFields)
	{
		$url = "/api/commerce/checkouts/{checkoutId}/items/{itemId}/split?quantity={quantity}&responseFields={responseFields}";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"POST", false) ;
		$url = $mozuUrl->formatUrl("checkoutId", $checkoutId);
		$url = $mozuUrl->formatUrl("itemId", $itemId);
		$url = $mozuUrl->formatUrl("quantity", $quantity);
		$url = $mozuUrl->formatUrl("responseFields", $responseFields);
		return $mozuUrl;
	}
	
	/**
		* Get Resource Url for BulkUpdateItemDestinations
		* @param string $checkoutId 
		* @param string $responseFields 
		* @return string Resource Url
	*/
	public static function bulkUpdateItemDestinationsUrl($checkoutId, $responseFields)
	{
		$url = "/api/commerce/checkouts/{checkoutId}/items/destinations?responseFields={responseFields}";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"POST", false) ;
		$url = $mozuUrl->formatUrl("checkoutId", $checkoutId);
		$url = $mozuUrl->formatUrl("responseFields", $responseFields);
		return $mozuUrl;
	}
	
	/**
		* Get Resource Url for AddCheckoutItem
		* @param string $checkoutId 
		* @param string $responseFields 
		* @return string Resource Url
	*/
	public static function addCheckoutItemUrl($checkoutId, $responseFields)
	{
		$url = "/api/commerce/checkouts/{checkoutId}/items?skipInventoryCheck={skipInventoryCheck}&responseFields={responseFields}";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"POST", false) ;
		$url = $mozuUrl->formatUrl("checkoutId", $checkoutId);
		$url = $mozuUrl->formatUrl("responseFields", $responseFields);
		return $mozuUrl;
	}
	
	/**
		* Get Resource Url for UpdateItemDestination
		* @param string $checkoutId 
		* @param string $destinationId 
		* @param string $itemId 
		* @param string $responseFields 
		* @return string Resource Url
	*/
	public static function updateItemDestinationUrl($checkoutId, $destinationId, $itemId, $responseFields)
	{
		$url = "/api/commerce/checkouts/{checkoutId}/items/{itemId}/destination/{destinationId}?responseFields={responseFields}";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"PUT", false) ;
		$url = $mozuUrl->formatUrl("checkoutId", $checkoutId);
		$url = $mozuUrl->formatUrl("destinationId", $destinationId);
		$url = $mozuUrl->formatUrl("itemId", $itemId);
		$url = $mozuUrl->formatUrl("responseFields", $responseFields);
		return $mozuUrl;
	}
	
	/**
		* Get Resource Url for DeleteCheckoutItem
		* @param string $checkoutId 
		* @param string $itemId 
		* @return string Resource Url
	*/
	public static function deleteCheckoutItemUrl($checkoutId, $itemId)
	{
		$url = "/api/commerce/checkouts/{checkoutId}/items/{itemId}";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"DELETE", false) ;
		$url = $mozuUrl->formatUrl("checkoutId", $checkoutId);
		$url = $mozuUrl->formatUrl("itemId", $itemId);
		return $mozuUrl;
	}
	
}

?>

