<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Urls\Commerce\Customer;

use Mozu\Api\MozuUrl;
use Mozu\Api\UrlLocation;

class CustomerAuthTicketUrl  {

	/**
		* Get Resource Url for CreateAnonymousShopperAuthTicket
		* @return string Resource Url
	*/
	public static function createAnonymousShopperAuthTicketUrl()
	{
		$url = "/api/commerce/customer/authtickets/anonymousshopper";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"GET", false) ;
		return $mozuUrl;
	}
	
	/**
		* Get Resource Url for CreateUserAuthTicket
		* @return string Resource Url
	*/
	public static function createUserAuthTicketUrl()
	{
		$url = "/api/commerce/customer/authtickets/";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"POST", false) ;
		return $mozuUrl;
	}
	
	/**
		* Get Resource Url for RefreshUserAuthTicket
		* @param string $refreshToken 
		* @return string Resource Url
	*/
	public static function refreshUserAuthTicketUrl($refreshToken)
	{
		$url = "/api/commerce/customer/authtickets/refresh?refreshToken={refreshToken}";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"PUT", false) ;
		$url = $mozuUrl->formatUrl("refreshToken", $refreshToken);
		return $mozuUrl;
	}
	
}

?>

