<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Urls\Commerce\Catalog\Admin\Attributedefinition\Producttypes;

use Mozu\Api\MozuUrl;
use Mozu\Api\UrlLocation;

class ProductTypeExtraUrl  {

	/**
		* Get Resource Url for GetExtras
		* @param int $productTypeId Identifier of the product type whose list is being retrieved.
		* @return string Resource Url
	*/
	public static function getExtrasUrl($productTypeId)
	{
		$url = "/api/commerce/catalog/admin/attributedefinition/producttypes/{productTypeId}/Extras";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"GET", false) ;
		$url = $mozuUrl->formatUrl("productTypeId", $productTypeId);
		return $mozuUrl;
	}
	
	/**
		* Get Resource Url for GetExtra
		* @param string $attributeFQN "The fully qualified name of the attribute, which is a user defined attribute identifier."
		* @param int $productTypeId Identifier of the product type whose extra is being retrieved.
		* @return string Resource Url
	*/
	public static function getExtraUrl($attributeFQN, $productTypeId)
	{
		$url = "/api/commerce/catalog/admin/attributedefinition/producttypes/{productTypeId}/Extras/{attributeFQN}";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"GET", false) ;
		$url = $mozuUrl->formatUrl("attributeFQN", $attributeFQN);
		$url = $mozuUrl->formatUrl("productTypeId", $productTypeId);
		return $mozuUrl;
	}
	
	/**
		* Get Resource Url for AddExtra
		* @param int $productTypeId Identifier of the product type to add an extra.
		* @return string Resource Url
	*/
	public static function addExtraUrl($productTypeId)
	{
		$url = "/api/commerce/catalog/admin/attributedefinition/producttypes/{productTypeId}/Extras";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"POST", false) ;
		$url = $mozuUrl->formatUrl("productTypeId", $productTypeId);
		return $mozuUrl;
	}
	
	/**
		* Get Resource Url for UpdateExtra
		* @param string $attributeFQN "The fully qualified name of the attribute, which is a user defined attribute identifier."
		* @param int $productTypeId Identifier of the product type whose extra is being updated.
		* @return string Resource Url
	*/
	public static function updateExtraUrl($attributeFQN, $productTypeId)
	{
		$url = "/api/commerce/catalog/admin/attributedefinition/producttypes/{productTypeId}/Extras/{attributeFQN}";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"PUT", false) ;
		$url = $mozuUrl->formatUrl("attributeFQN", $attributeFQN);
		$url = $mozuUrl->formatUrl("productTypeId", $productTypeId);
		return $mozuUrl;
	}
	
	/**
		* Get Resource Url for DeleteExtra
		* @param string $attributeFQN "The fully qualified name of the attribute, which is a user defined attribute identifier."
		* @param int $productTypeId Identifier of the product type whose extra is being deleted.
		* @return string Resource Url
	*/
	public static function deleteExtraUrl($attributeFQN, $productTypeId)
	{
		$url = "/api/commerce/catalog/admin/attributedefinition/producttypes/{productTypeId}/Extras/{attributeFQN}";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"DELETE", false) ;
		$url = $mozuUrl->formatUrl("attributeFQN", $attributeFQN);
		$url = $mozuUrl->formatUrl("productTypeId", $productTypeId);
		return $mozuUrl;
	}
	
}

?>

