<?php


/**
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

namespace Mozu\Api\Clients\Commerce\Customer\Accounts;

use Mozu\Api\MozuClient;
use Mozu\Api\Urls\Commerce\Customer\Accounts\TransactionUrl;
use Mozu\Api\Headers;

use Mozu\Api\Contracts\Customer\Transaction;

/**
* Use the Customer Account Transactions resource to manage the transactions associated with a customer account.
*/
class TransactionClient {

	/**
	* Retrieves a list of transactions associated with the customer account specified in the request.
	*
	* @param int $accountId Unique identifier of the customer account for which to retrieve transactions.
	* @return MozuClient
	*/
	public static function getTransactionsClient($accountId)
	{
		$url = TransactionUrl::getTransactionsUrl($accountId);
		$mozuClient = new MozuClient();
		return $mozuClient->withResourceUrl($url);

	}
	
	/**
	* Creates a new transaction for the customer account specified in the request.
	*
	* @param int $accountId Unique identifier of the customer account.
	* @param string $responseFields Use this field to include those fields which are not included by default.
	* @param Transaction $transaction Properties of the transaction to create for the customer account.
	* @return MozuClient
	*/
	public static function addTransactionClient($transaction, $accountId, $responseFields =  null)
	{
		$url = TransactionUrl::addTransactionUrl($accountId, $responseFields);
		$mozuClient = new MozuClient();
		return $mozuClient->withResourceUrl($url)->withBody($transaction);

	}
	
	/**
	* Deletes a transaction from the customer account specified in the request.
	*
	* @param int $accountId Unique identifier of the customer account from which to delete the transaction.
	* @param string $transactionId Unique identifier of the transaction to delete.
	* @return MozuClient
	*/
	public static function removeTransactionClient($accountId, $transactionId)
	{
		$url = TransactionUrl::removeTransactionUrl($accountId, $transactionId);
		$mozuClient = new MozuClient();
		return $mozuClient->withResourceUrl($url);

	}
	
	
}

?>

