<?php


/**
* <auto-generated>
*     This code was generated by Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

namespace Mozu\Api\Clients\Commerce\Carts;

use Mozu\Api\MozuClient;
use Mozu\Api\Urls\Commerce\Carts\AppliedDiscountUrl;


/**
* Use the Cart Coupons resource to apply a coupon to a defined cart or remove a coupon from a cart. When the shopper proceeds to checkout, the coupons applied to the cart apply to the order.
*/
class AppliedDiscountClient {

	/**
	* 
	*
	* @param string $cartId Unique identifier of the cart to which to apply the coupon.
	* @param string $couponCode Code associated with the coupon to apply to the cart.
	* @param string $responseFields 
	* @return MozuClient
	*/
	public static function applyCouponClient($cartId, $couponCode, $responseFields =  null)
	{
		$url = AppliedDiscountUrl::applyCouponUrl($cartId, $couponCode, $responseFields);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url);
		return $mozuClient;

	}
	
	/**
	* 
	*
	* @param string $cartId Unique identifier of the cart.
	* @return MozuClient
	*/
	public static function removeCouponsClient($cartId)
	{
		$url = AppliedDiscountUrl::removeCouponsUrl($cartId);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url);
		return $mozuClient;

	}
	
	/**
	* 
	*
	* @param string $cartId Unique identifier of the cart.
	* @param string $couponCode Code associated with the coupon to remove from the cart.
	* @return MozuClient
	*/
	public static function removeCouponClient($cartId, $couponCode)
	{
		$url = AppliedDiscountUrl::removeCouponUrl($cartId, $couponCode);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url);
		return $mozuClient;

	}
	
	
}

?>

