<?php


/**
* <auto-generated>
*     This code was generated by Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

namespace Mozu\Api\Resources\Content;

use Mozu\Api\Clients\Content\DocumentListTypeClient;
use Mozu\Api\ApiContext;

use Mozu\Api\Headers;

/**
* Use the Document List Types resource to manage the types of document lists in your site's document hierarchy. The type denotes a content type for that list of folders, sub-folders, and documents such as `web_pages`.
*/
class DocumentListTypeResource {

		private $apiContext;
		private $dataViewMode;
		public function __construct(ApiContext $apiContext, $dataViewMode) 
	{
		$this->apiContext = $apiContext;
		$this->dataViewMode = $dataViewMode;
	}
	



	/**
	* content-documentlistTypes Get GetDocumentListTypes description DOCUMENT_HERE 
	*
	* @param int $pageSize When creating paged results from a query, this value indicates the zero-based offset in the complete result set where the returned entities begin. For example, with this parameter set to 25, to get the 51st through the 75th items, set startIndex to 50.
	* @param string $responseFields Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.
	* @param int $startIndex When creating paged results from a query, this value indicates the zero-based offset in the complete result set where the returned entities begin. For example, with pageSize set to 25, to get the 51st through the 75th items, set this parameter to 50.
	* @return DocumentListTypeCollection 
	* @deprecated deprecated since version 1.17
	*/
	public function getDocumentListTypes($pageSize =  null, $startIndex =  null, $responseFields =  null)
	{
		$mozuClient = DocumentListTypeClient::getDocumentListTypesClient($this->dataViewMode, $pageSize, $startIndex, $responseFields);
		$mozuClient = $mozuClient->withContext($this->apiContext);
		$mozuClient->execute();
		return $mozuClient->getResult();

	}
	
/**
	* content-documentlistTypes Get GetDocumentListTypes description DOCUMENT_HERE 
	*
	* @param int $pageSize When creating paged results from a query, this value indicates the zero-based offset in the complete result set where the returned entities begin. For example, with this parameter set to 25, to get the 51st through the 75th items, set startIndex to 50.
	* @param string $responseFields Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.
	* @param int $startIndex When creating paged results from a query, this value indicates the zero-based offset in the complete result set where the returned entities begin. For example, with pageSize set to 25, to get the 51st through the 75th items, set this parameter to 50.
	* @return Promise - use $promise->then(sucessfn, errorfn). successFn is passed Mozu\Api\MozuResult. errorFn is passed Mozu\Api\ApiException
	*/
	public function getDocumentListTypesAsync($pageSize =  null, $startIndex =  null, $responseFields =  null)
	{
		$mozuClient = DocumentListTypeClient::getDocumentListTypesClient($this->dataViewMode, $pageSize, $startIndex, $responseFields);
		$mozuClient = $mozuClient->withContext($this->apiContext);
		return $mozuClient->executeAsync();

	}
	
	/**
	* content-documentlistTypes Get GetDocumentListType description DOCUMENT_HERE 
	*
	* @param string $documentListTypeFQN 
	* @param string $responseFields Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.
	* @return DocumentListType 
	* @deprecated deprecated since version 1.17
	*/
	public function getDocumentListType($documentListTypeFQN, $responseFields =  null)
	{
		$mozuClient = DocumentListTypeClient::getDocumentListTypeClient($this->dataViewMode, $documentListTypeFQN, $responseFields);
		$mozuClient = $mozuClient->withContext($this->apiContext);
		$mozuClient->execute();
		return $mozuClient->getResult();

	}
	
/**
	* content-documentlistTypes Get GetDocumentListType description DOCUMENT_HERE 
	*
	* @param string $documentListTypeFQN 
	* @param string $responseFields Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.
	* @return Promise - use $promise->then(sucessfn, errorfn). successFn is passed Mozu\Api\MozuResult. errorFn is passed Mozu\Api\ApiException
	*/
	public function getDocumentListTypeAsync($documentListTypeFQN, $responseFields =  null)
	{
		$mozuClient = DocumentListTypeClient::getDocumentListTypeClient($this->dataViewMode, $documentListTypeFQN, $responseFields);
		$mozuClient = $mozuClient->withContext($this->apiContext);
		return $mozuClient->executeAsync();

	}
	
	/**
	* Creates a new documentListType
	*
	* @param string $responseFields Use this field to include those fields which are not included by default.
	* @param DocumentListType $list Properties for the document list type. Document lists contain documents with an associated document type, such as web pages.
	* @return DocumentListType 
	* @deprecated deprecated since version 1.17
	*/
	public function createDocumentListType($list, $responseFields =  null)
	{
		$mozuClient = DocumentListTypeClient::createDocumentListTypeClient($this->dataViewMode, $list, $responseFields);
		$mozuClient = $mozuClient->withContext($this->apiContext);
		$mozuClient->execute();
		return $mozuClient->getResult();

	}
	
/**
	* Creates a new documentListType
	*
	* @param string $responseFields Use this field to include those fields which are not included by default.
	* @return Promise - use $promise->then(sucessfn, errorfn). successFn is passed Mozu\Api\MozuResult. errorFn is passed Mozu\Api\ApiException
	*/
	public function createDocumentListTypeAsync($list, $responseFields =  null)
	{
		$mozuClient = DocumentListTypeClient::createDocumentListTypeClient($this->dataViewMode, $list, $responseFields);
		$mozuClient = $mozuClient->withContext($this->apiContext);
		return $mozuClient->executeAsync();

	}
	
	/**
	* Updates a DocumentListType
	*
	* @param string $documentListTypeFQN 
	* @param string $responseFields Use this field to include those fields which are not included by default.
	* @param DocumentListType $list Properties for the document list type. Document lists contain documents with an associated document type, such as web pages.
	* @return DocumentListType 
	* @deprecated deprecated since version 1.17
	*/
	public function updateDocumentListType($list, $documentListTypeFQN, $responseFields =  null)
	{
		$mozuClient = DocumentListTypeClient::updateDocumentListTypeClient($list, $documentListTypeFQN, $responseFields);
		$mozuClient = $mozuClient->withContext($this->apiContext);
		$mozuClient->execute();
		return $mozuClient->getResult();

	}
	
/**
	* Updates a DocumentListType
	*
	* @param string $documentListTypeFQN 
	* @param string $responseFields Use this field to include those fields which are not included by default.
	* @return Promise - use $promise->then(sucessfn, errorfn). successFn is passed Mozu\Api\MozuResult. errorFn is passed Mozu\Api\ApiException
	*/
	public function updateDocumentListTypeAsync($list, $documentListTypeFQN, $responseFields =  null)
	{
		$mozuClient = DocumentListTypeClient::updateDocumentListTypeClient($list, $documentListTypeFQN, $responseFields);
		$mozuClient = $mozuClient->withContext($this->apiContext);
		return $mozuClient->executeAsync();

	}
	
	
}

?>

