<?php

/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Urls\Commerce\Customer\Accounts;

use Mozu\Api\MozuUrl;
use Mozu\Api\UrlLocation;

class CardUrl  {

	/**
		* Get Resource Url for GetAccountCards
		* @param int $accountId 
		* @return string Resource Url
	*/
	public static function getAccountCardsUrl($accountId)
	{
		$url = "/api/commerce/customer/accounts/{accountId}/cards";
		$url = MozuUrl::formatUrl($url, "accountId", $accountId);
		return new MozuUrl($url, UrlLocation::TENANT_POD,"GET") ;
	}
	
	/**
		* Get Resource Url for AddAccountCard
		* @param int $accountId 
		* @return string Resource Url
	*/
	public static function addAccountCardUrl($accountId)
	{
		$url = "/api/commerce/customer/accounts/{accountId}/cards";
		$url = MozuUrl::formatUrl($url, "accountId", $accountId);
		return new MozuUrl($url, UrlLocation::TENANT_POD,"POST") ;
	}
	
	/**
		* Get Resource Url for UpdateAccountCard
		* @param int $accountId 
		* @return string Resource Url
	*/
	public static function updateAccountCardUrl($accountId)
	{
		$url = "/api/commerce/customer/accounts/{accountId}/cards";
		$url = MozuUrl::formatUrl($url, "accountId", $accountId);
		return new MozuUrl($url, UrlLocation::TENANT_POD,"PUT") ;
	}
	
	/**
		* Get Resource Url for DeleteAccountCard
		* @param int $accountId 
		* @param string $cardId 
		* @return string Resource Url
	*/
	public static function deleteAccountCardUrl($accountId, $cardId)
	{
		$url = "/api/commerce/customer/accounts/{accountId}/cards/{cardId}";
		$url = MozuUrl::formatUrl($url, "accountId", $accountId);
		$url = MozuUrl::formatUrl($url, "cardId", $cardId);
		return new MozuUrl($url, UrlLocation::TENANT_POD,"DELETE") ;
	}
	
}

?>

