<?php

/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Urls\Commerce\Customer\Accounts;

use Mozu\Api\Urls\BaseUrl;

class CustomerContactUrl extends BaseUrl {

	/**
		* Get Resource Url for GetAccountContact
		* @param int $accountId Unique identifier of the customer account whose contact information is being retrieved.
		* @param int $contactId Unique identifier of the customer account contact to retrieve.
		* @return string Resource Url
	*/
	public static function getAccountContactUrl($accountId, $contactId)
	{
		$url = "/api/commerce/customer/accounts/{accountId}/contacts/{contactId}";
		$url = parent::formatUrl($url, "accountId", $accountId);
		$url = parent::formatUrl($url, "contactId", $contactId);
		return $url;
	}
	
	/**
		* Get Resource Url for GetAccountContacts
		* @param int $accountId Unique identifier of the customer account associated with the contact information to retrieve.
		* @param string $filter A set of expressions that consist of a field, operator, and value and represent search parameter syntax when filtering results of a query. Valid operators include equals (eq), does not equal (ne), greater than (gt), less than (lt), greater than or equal to (ge), less than or equal to (le), starts with (sw), or contains (cont). For example - "filter=IsDisplayed+eq+true"
		* @param int $pageSize Specifies the number of results to display on each page when creating paged results from a query. The maximum value is 200.
		* @param string $sortBy 
		* @param int $startIndex 
		* @return string Resource Url
	*/
	public static function getAccountContactsUrl($accountId, $filter, $pageSize, $sortBy, $startIndex)
	{
		$url = "/api/commerce/customer/accounts/{accountId}/contacts?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}";
		$url = parent::formatUrl($url, "accountId", $accountId);
		$url = parent::formatUrl($url, "filter", $filter);
		$url = parent::formatUrl($url, "pageSize", $pageSize);
		$url = parent::formatUrl($url, "sortBy", $sortBy);
		$url = parent::formatUrl($url, "startIndex", $startIndex);
		return $url;
	}
	
	/**
		* Get Resource Url for AddAccountContact
		* @param int $accountId Unique identifier of the customer account containing the new contact.
		* @return string Resource Url
	*/
	public static function addAccountContactUrl($accountId)
	{
		$url = "/api/commerce/customer/accounts/{accountId}/contacts";
		$url = parent::formatUrl($url, "accountId", $accountId);
		return $url;
	}
	
	/**
		* Get Resource Url for UpdateAccountContact
		* @param int $accountId Unique identifier of the customer account whose contact information is being updated.
		* @param int $contactId Unique identifer of the customer account contact being updated.
		* @return string Resource Url
	*/
	public static function updateAccountContactUrl($accountId, $contactId)
	{
		$url = "/api/commerce/customer/accounts/{accountId}/contacts/{contactId}";
		$url = parent::formatUrl($url, "accountId", $accountId);
		$url = parent::formatUrl($url, "contactId", $contactId);
		return $url;
	}
	
	/**
		* Get Resource Url for DeleteAccountContact
		* @param int $accountId Unique identifier of the customer account.
		* @param int $contactId Unique identifier of the customer account contact to delete.
		* @return string Resource Url
	*/
	public static function deleteAccountContactUrl($accountId, $contactId)
	{
		$url = "/api/commerce/customer/accounts/{accountId}/contacts/{contactId}";
		$url = parent::formatUrl($url, "accountId", $accountId);
		$url = parent::formatUrl($url, "contactId", $contactId);
		return $url;
	}
	
}

?>

