<?php


/**
* <auto-generated>
*     This code was generated by Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

namespace Mozu\Api\Clients\Content\Documentlists;

use Mozu\Api\MozuClient;
use Mozu\Api\Urls\Content\Documentlists\FacetUrl;


/**
* Use the facets subresource to allow a merchant to add information for product indexing and searching.
*/
class FacetClient {

	/**
	* Retrieves the properties of facets that aid in indexing and searching.
	*
	* @param string $documentListName Name of content documentListName to delete
	* @param string $propertyName The property name associated with the facets to retrieve.
	* @return MozuClient
	*/
	public static function getFacetsClient($documentListName, $propertyName)
	{
		$url = FacetUrl::getFacetsUrl($documentListName, $propertyName);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url);
		return $mozuClient;

	}
	
	
}

?>

