<?php

/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Urls\Commerce\Catalog\Admin;

use Mozu\Api\Urls\BaseUrl;

class DiscountUrl extends BaseUrl {

	/**
		* Get Resource Url for GetDiscounts
		* @param string $filter A set of expressions that consist of a field, operator, and value and represent search parameter syntax when filtering results of a query. Valid operators include equals (eq), does not equal (ne), greater than (gt), less than (lt), greater than or equal to (ge), less than or equal to (le), starts with (sw), or contains (cont). For example - "filter=IsDisplayed+eq+true"
		* @param int $pageSize Specifies the number of results to display on each page when creating paged results from a query. The maximum value is 200.
		* @param string $sortBy 
		* @param int $startIndex 
		* @return string Resource Url
	*/
	public static function getDiscountsUrl($filter, $pageSize, $sortBy, $startIndex)
	{
		$url = "/api/commerce/catalog/admin/discounts/?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&";
		$url = parent::formatUrl($url, "filter", $filter);
		$url = parent::formatUrl($url, "pageSize", $pageSize);
		$url = parent::formatUrl($url, "sortBy", $sortBy);
		$url = parent::formatUrl($url, "startIndex", $startIndex);
		return $url;
	}
	
	/**
		* Get Resource Url for GetDiscount
		* @param int $discountId Unique identifier of the discount. System-supplied and read-only.
		* @return string Resource Url
	*/
	public static function getDiscountUrl($discountId)
	{
		$url = "/api/commerce/catalog/admin/discounts/{discountId}";
		$url = parent::formatUrl($url, "discountId", $discountId);
		return $url;
	}
	
	/**
		* Get Resource Url for GetDiscountContent
		* @param int $discountId Unique identifier of the discount. System-supplied and read-only.
		* @return string Resource Url
	*/
	public static function getDiscountContentUrl($discountId)
	{
		$url = "/api/commerce/catalog/admin/discounts/{discountId}/content";
		$url = parent::formatUrl($url, "discountId", $discountId);
		return $url;
	}
	
	/**
		* Get Resource Url for GenerateRandomCoupon
		* @return string Resource Url
	*/
	public static function generateRandomCouponUrl()
	{
		$url = "/api/commerce/catalog/admin/discounts/generate-random-coupon";
		return $url;
	}
	
	/**
		* Get Resource Url for CreateDiscount
		* @return string Resource Url
	*/
	public static function createDiscountUrl()
	{
		$url = "/api/commerce/catalog/admin/discounts/";
		return $url;
	}
	
	/**
		* Get Resource Url for RedeemDiscount
		* @return string Resource Url
	*/
	public static function redeemDiscountUrl()
	{
		$url = "/api/commerce/catalog/admin/discounts/Redeem";
		return $url;
	}
	
	/**
		* Get Resource Url for UpdateDiscount
		* @param int $discountId Unique identifier of the discount. System-supplied and read-only.
		* @return string Resource Url
	*/
	public static function updateDiscountUrl($discountId)
	{
		$url = "/api/commerce/catalog/admin/discounts/{discountId}";
		$url = parent::formatUrl($url, "discountId", $discountId);
		return $url;
	}
	
	/**
		* Get Resource Url for UpdateDiscountContent
		* @param int $discountId Unique identifier of the discount. System-supplied and read-only.
		* @return string Resource Url
	*/
	public static function updateDiscountContentUrl($discountId)
	{
		$url = "/api/commerce/catalog/admin/discounts/{discountId}/content";
		$url = parent::formatUrl($url, "discountId", $discountId);
		return $url;
	}
	
	/**
		* Get Resource Url for DeleteDiscount
		* @param int $discountId Unique identifier of the discount. System-supplied and read-only.
		* @return string Resource Url
	*/
	public static function deleteDiscountUrl($discountId)
	{
		$url = "/api/commerce/catalog/admin/discounts/{discountId}";
		$url = parent::formatUrl($url, "discountId", $discountId);
		return $url;
	}
	
	/**
		* Get Resource Url for UnRedeemDiscount
		* @param int $discountId Unique identifier of the previously redeemed discount. System-supplied and read only.
		* @param int $orderNumber The number of the order associated with the redeemed product discount.
		* @return string Resource Url
	*/
	public static function unRedeemDiscountUrl($discountId, $orderNumber)
	{
		$url = "/api/commerce/catalog/admin/discounts/{discountId}/Unredeem/{orderNumber}";
		$url = parent::formatUrl($url, "discountId", $discountId);
		$url = parent::formatUrl($url, "orderNumber", $orderNumber);
		return $url;
	}
	
}

?>

