<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Urls\Platform;

use Mozu\Api\MozuUrl;
use Mozu\Api\UrlLocation;

class ApplicationUrl  {

	/**
		* Get Resource Url for GetApplication
		* @param string $appId 
		* @return string Resource Url
	*/
	public static function getApplicationUrl($appId)
	{
		$url = "/api/platform/applications/{appId}";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"GET", false) ;
		$url = $mozuUrl->formatUrl("appId", $appId);
		return $mozuUrl;
	}
	
	/**
		* Get Resource Url for UpdateApplication
		* @param string $appId 
		* @return string Resource Url
	*/
	public static function updateApplicationUrl($appId)
	{
		$url = "/api/platform/applications/{appId}";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"PUT", false) ;
		$url = $mozuUrl->formatUrl("appId", $appId);
		return $mozuUrl;
	}
	
}

?>

