<?php


/**
* <auto-generated>
*     This code was generated by Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

namespace Mozu\Api\Clients\Commerce\Catalog\Admin\Products;

use Mozu\Api\MozuClient;
use Mozu\Api\Urls\Commerce\Catalog\Admin\Products\ProductOptionUrl;

use Mozu\Api\Headers;

/**
* Use the Options resource to configure the option attributes and vocabulary values for an individual product associated with the product type that uses the option attribute. Options are used to generate variations of a product.
*/
class ProductOptionClient {

	/**
	* 
	*
	* @param string $productCode 
	* @return MozuClient
	*/
	public static function getOptionsClient($dataViewMode, $productCode)
	{
		$url = ProductOptionUrl::getOptionsUrl($productCode);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url)->withHeader(Headers::X_VOL_DATAVIEW_MODE ,$dataViewMode);
		return $mozuClient;

	}
	
	/**
	* 
	*
	* @param string $attributeFQN 
	* @param string $productCode 
	* @param string $responseFields 
	* @return MozuClient
	*/
	public static function getOptionClient($dataViewMode, $productCode, $attributeFQN, $responseFields =  null)
	{
		$url = ProductOptionUrl::getOptionUrl($attributeFQN, $productCode, $responseFields);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url)->withHeader(Headers::X_VOL_DATAVIEW_MODE ,$dataViewMode);
		return $mozuClient;

	}
	
	/**
	* 
	*
	* @param string $productCode 
	* @param string $responseFields 
	* @param ProductOption $productOption Properties of the option attribute to define for the product.
	* @return MozuClient
	*/
	public static function addOptionClient($dataViewMode, $productOption, $productCode, $responseFields =  null)
	{
		$url = ProductOptionUrl::addOptionUrl($productCode, $responseFields);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url)->withBody($productOption)->withHeader(Headers::X_VOL_DATAVIEW_MODE ,$dataViewMode);
		return $mozuClient;

	}
	
	/**
	* 
	*
	* @param string $attributeFQN 
	* @param string $productCode 
	* @param string $responseFields 
	* @param ProductOption $productOption Properties of the product option attribute configuration to update.
	* @return MozuClient
	*/
	public static function updateOptionClient($dataViewMode, $productOption, $productCode, $attributeFQN, $responseFields =  null)
	{
		$url = ProductOptionUrl::updateOptionUrl($attributeFQN, $productCode, $responseFields);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url)->withBody($productOption)->withHeader(Headers::X_VOL_DATAVIEW_MODE ,$dataViewMode);
		return $mozuClient;

	}
	
	/**
	* 
	*
	* @param string $attributeFQN 
	* @param string $productCode 
	* @return MozuClient
	*/
	public static function deleteOptionClient($dataViewMode, $productCode, $attributeFQN)
	{
		$url = ProductOptionUrl::deleteOptionUrl($attributeFQN, $productCode);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url)->withHeader(Headers::X_VOL_DATAVIEW_MODE ,$dataViewMode);
		return $mozuClient;

	}
	
	
}

?>

