<?php


/**
* <auto-generated>
*     This code was generated by Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

namespace Mozu\Api\Clients\Commerce\Catalog\Admin\Products;

use Mozu\Api\MozuClient;
use Mozu\Api\Urls\Commerce\Catalog\Admin\Products\ProductPropertyUrl;

use Mozu\Api\Headers;

/**
* Use the Properties resource to configure a property attribute for an individual product associated with a product type that uses the property attribute, as well as set property values for the product.
*/
class ProductPropertyClient {

	/**
	* 
	*
	* @param string $productCode 
	* @return MozuClient
	*/
	public static function getPropertiesClient($dataViewMode, $productCode)
	{
		$url = ProductPropertyUrl::getPropertiesUrl($productCode);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url)->withHeader(Headers::X_VOL_DATAVIEW_MODE ,$dataViewMode);
		return $mozuClient;

	}
	
	/**
	* 
	*
	* @param string $attributeFQN 
	* @param string $productCode 
	* @param string $value 
	* @return MozuClient
	*/
	public static function getPropertyValueLocalizedContentsClient($dataViewMode, $productCode, $attributeFQN, $value)
	{
		$url = ProductPropertyUrl::getPropertyValueLocalizedContentsUrl($attributeFQN, $productCode, $value);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url)->withHeader(Headers::X_VOL_DATAVIEW_MODE ,$dataViewMode);
		return $mozuClient;

	}
	
	/**
	* 
	*
	* @param string $attributeFQN 
	* @param string $localeCode 
	* @param string $productCode 
	* @param string $responseFields 
	* @param string $value 
	* @return MozuClient
	*/
	public static function getPropertyValueLocalizedContentClient($dataViewMode, $productCode, $attributeFQN, $value, $localeCode, $responseFields =  null)
	{
		$url = ProductPropertyUrl::getPropertyValueLocalizedContentUrl($attributeFQN, $localeCode, $productCode, $responseFields, $value);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url)->withHeader(Headers::X_VOL_DATAVIEW_MODE ,$dataViewMode);
		return $mozuClient;

	}
	
	/**
	* 
	*
	* @param string $attributeFQN 
	* @param string $productCode 
	* @param string $responseFields 
	* @return MozuClient
	*/
	public static function getPropertyClient($dataViewMode, $productCode, $attributeFQN, $responseFields =  null)
	{
		$url = ProductPropertyUrl::getPropertyUrl($attributeFQN, $productCode, $responseFields);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url)->withHeader(Headers::X_VOL_DATAVIEW_MODE ,$dataViewMode);
		return $mozuClient;

	}
	
	/**
	* 
	*
	* @param string $attributeFQN 
	* @param string $productCode 
	* @param string $responseFields 
	* @param string $value 
	* @param ProductPropertyValueLocalizedContent $localizedContent 
	* @return MozuClient
	*/
	public static function addPropertyValueLocalizedContentClient($dataViewMode, $localizedContent, $productCode, $attributeFQN, $value, $responseFields =  null)
	{
		$url = ProductPropertyUrl::addPropertyValueLocalizedContentUrl($attributeFQN, $productCode, $responseFields, $value);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url)->withBody($localizedContent)->withHeader(Headers::X_VOL_DATAVIEW_MODE ,$dataViewMode);
		return $mozuClient;

	}
	
	/**
	* 
	*
	* @param string $productCode 
	* @param string $responseFields 
	* @param ProductProperty $productProperty Properties of the property attribute to configure for a product.
	* @return MozuClient
	*/
	public static function addPropertyClient($dataViewMode, $productProperty, $productCode, $responseFields =  null)
	{
		$url = ProductPropertyUrl::addPropertyUrl($productCode, $responseFields);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url)->withBody($productProperty)->withHeader(Headers::X_VOL_DATAVIEW_MODE ,$dataViewMode);
		return $mozuClient;

	}
	
	/**
	* 
	*
	* @param string $attributeFQN 
	* @param string $productCode 
	* @param string $value 
	* @param array|ProductPropertyValueLocalizedContent $localizedContent 
	* @return MozuClient
	*/
	public static function updatePropertyValueLocalizedContentsClient($dataViewMode, $localizedContent, $productCode, $attributeFQN, $value)
	{
		$url = ProductPropertyUrl::updatePropertyValueLocalizedContentsUrl($attributeFQN, $productCode, $value);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url)->withBody($localizedContent)->withHeader(Headers::X_VOL_DATAVIEW_MODE ,$dataViewMode);
		return $mozuClient;

	}
	
	/**
	* 
	*
	* @param string $attributeFQN 
	* @param string $localeCode 
	* @param string $productCode 
	* @param string $responseFields 
	* @param string $value 
	* @param ProductPropertyValueLocalizedContent $localizedContent 
	* @return MozuClient
	*/
	public static function updatePropertyValueLocalizedContentClient($dataViewMode, $localizedContent, $productCode, $attributeFQN, $value, $localeCode, $responseFields =  null)
	{
		$url = ProductPropertyUrl::updatePropertyValueLocalizedContentUrl($attributeFQN, $localeCode, $productCode, $responseFields, $value);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url)->withBody($localizedContent)->withHeader(Headers::X_VOL_DATAVIEW_MODE ,$dataViewMode);
		return $mozuClient;

	}
	
	/**
	* 
	*
	* @param string $attributeFQN 
	* @param string $productCode 
	* @param string $responseFields 
	* @param ProductProperty $productProperty Details of the property attribute to update for the product configuration.
	* @return MozuClient
	*/
	public static function updatePropertyClient($dataViewMode, $productProperty, $productCode, $attributeFQN, $responseFields =  null)
	{
		$url = ProductPropertyUrl::updatePropertyUrl($attributeFQN, $productCode, $responseFields);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url)->withBody($productProperty)->withHeader(Headers::X_VOL_DATAVIEW_MODE ,$dataViewMode);
		return $mozuClient;

	}
	
	/**
	* 
	*
	* @param string $attributeFQN 
	* @param string $productCode 
	* @return MozuClient
	*/
	public static function deletePropertyClient($dataViewMode, $productCode, $attributeFQN)
	{
		$url = ProductPropertyUrl::deletePropertyUrl($attributeFQN, $productCode);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url)->withHeader(Headers::X_VOL_DATAVIEW_MODE ,$dataViewMode);
		return $mozuClient;

	}
	
	/**
	* 
	*
	* @param string $attributeFQN 
	* @param string $localeCode 
	* @param string $productCode 
	* @param string $value 
	* @return MozuClient
	*/
	public static function deletePropertyValueLocalizedContentClient($dataViewMode, $productCode, $attributeFQN, $value, $localeCode)
	{
		$url = ProductPropertyUrl::deletePropertyValueLocalizedContentUrl($attributeFQN, $localeCode, $productCode, $value);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url)->withHeader(Headers::X_VOL_DATAVIEW_MODE ,$dataViewMode);
		return $mozuClient;

	}
	
	
}

?>

