<?php

/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\ProductAdmin;



class AttributeVocabularyValue
{
		public $value;
	public function getValue() {
		return $this->value;
	}
	
	public function setValue($value) {
		$this->value = $value;
		return $this;
	}

		public $valueSequence;
	public function getValueSequence() {
		return $this->valueSequence;
	}
	
	public function setValueSequence($valueSequence) {
		$this->valueSequence = $valueSequence;
		return $this;
	}

		public $content;
	public function getContent() {
		return $this->content;
	}
	
	public function setContent($content) {
		$this->content = $content;
		return $this;
	}

}

?>
