<?php

/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\ProductAdmin;



class FacetSource
{
		public $allowsRangeQuery;
	public function getAllowsRangeQuery() {
		return $this->allowsRangeQuery;
	}
	
	public function setAllowsRangeQuery($allowsRangeQuery) {
		$this->allowsRangeQuery = $allowsRangeQuery;
		return $this;
	}

		public $dataType;
	public function getDataType() {
		return $this->dataType;
	}
	
	public function setDataType($dataType) {
		$this->dataType = $dataType;
		return $this;
	}

		public $id;
	public function getId() {
		return $this->id;
	}
	
	public function setId($id) {
		$this->id = $id;
		return $this;
	}

		public $name;
	public function getName() {
		return $this->name;
	}
	
	public function setName($name) {
		$this->name = $name;
		return $this;
	}

		public $type;
	public function getType() {
		return $this->type;
	}
	
	public function setType($type) {
		$this->type = $type;
		return $this;
	}

}

?>
