<?php


/**
* <auto-generated>
*     This code was generated by Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

namespace Mozu\Api\Clients\Commerce\Orders;

use Mozu\Api\MozuClient;
use Mozu\Api\Urls\Commerce\Orders\CanceledReasonUrl;


/**
* 
*/
class CanceledReasonClient {

	/**
	* 
	*
	* @param string $category 
	* @param string $responseFields 
	* @return MozuClient
	*/
	public static function getReasonsClient($category =  null, $responseFields =  null)
	{
		$url = CanceledReasonUrl::getReasonsUrl($category, $responseFields);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url);
		return $mozuClient;

	}
	
	/**
	* 
	*
	* @param string $orderId 
	* @param string $responseFields 
	* @param CanceledReason $reason 
	* @return MozuClient
	*/
	public static function cancelOrderClient($reason, $orderId, $responseFields =  null)
	{
		$url = CanceledReasonUrl::cancelOrderUrl($orderId, $responseFields);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url)->withBody($reason);
		return $mozuClient;

	}
	
	
}

?>

