<?php


/**
* <auto-generated>
*     This code was generated by Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

namespace Mozu\Api\Clients\Commerce\Orders;

use Mozu\Api\MozuClient;
use Mozu\Api\Urls\Commerce\Orders\RefundUrl;


/**
* 
*/
class RefundClient {

	/**
	* 
	*
	* @param string $orderId 
	* @param string $responseFields 
	* @param Refund $refund 
	* @return MozuClient
	*/
	public static function createRefundClient($refund, $orderId, $responseFields =  null)
	{
		$url = RefundUrl::createRefundUrl($orderId, $responseFields);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url)->withBody($refund);
		return $mozuClient;

	}
	
	/**
	* 
	*
	* @param string $orderId 
	* @param string $refundId 
	* @return MozuClient
	*/
	public static function resendRefundEmailClient($orderId, $refundId)
	{
		$url = RefundUrl::resendRefundEmailUrl($orderId, $refundId);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url);
		return $mozuClient;

	}
	
	
}

?>

