<?php


/**
* <auto-generated>
*     This code was generated by Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

namespace Mozu\Api\Resources\Commerce\Orders;

use Mozu\Api\Clients\Commerce\Orders\RefundClient;
use Mozu\Api\ApiContext;


/**
* Use the refunds resource to create a refund.
*/
class RefundResource {

		private $apiContext;
			
	public function __construct(ApiContext $apiContext) 
	{
		$this->apiContext = $apiContext;
	}

	



	/**
	* Creates a refund based on the information supplied in the request.  
	*
	* @param string $orderId Unique identifier of the order.
	* @param string $responseFields Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.
	* @param Refund $refund Mozu.CommerceRuntime.Contracts.Refunds.Refund ApiType DOCUMENT_HERE 
	* @return Refund 
	* @deprecated deprecated since version 1.17
	*/
	public function createRefund($refund, $orderId, $responseFields =  null)
	{
		$mozuClient = RefundClient::createRefundClient($refund, $orderId, $responseFields);
		$mozuClient = $mozuClient->withContext($this->apiContext);
		$mozuClient->execute();
		return $mozuClient->getResult();

	}
	
/**
	* Creates a refund based on the information supplied in the request.  
	*
	* @param string $orderId Unique identifier of the order.
	* @param string $responseFields Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.
	* @return Promise - use $promise->then(sucessfn, errorfn). successFn is passed Mozu\Api\MozuResult. errorFn is passed Mozu\Api\ApiException
	*/
	public function createRefundAsync($refund, $orderId, $responseFields =  null)
	{
		$mozuClient = RefundClient::createRefundClient($refund, $orderId, $responseFields);
		$mozuClient = $mozuClient->withContext($this->apiContext);
		return $mozuClient->executeAsync();

	}
	
	/**
	* Resends the order refund email previously sent to the shopper. 
	*
	* @param string $orderId Unique identifier of the order.
	* @param string $refundId Unique ID of the refund.
        
	* @deprecated deprecated since version 1.17
	*/
	public function resendRefundEmail($orderId, $refundId)
	{
		$mozuClient = RefundClient::resendRefundEmailClient($orderId, $refundId);
		$mozuClient = $mozuClient->withContext($this->apiContext);
		$mozuClient->execute();

	}
	
/**
	* Resends the order refund email previously sent to the shopper. 
	*
	* @param string $orderId Unique identifier of the order.
	* @param string $refundId Unique ID of the refund.
        
	* @return Promise - use $promise->then(sucessfn, errorfn). successFn is passed Mozu\Api\MozuResult. errorFn is passed Mozu\Api\ApiException
	*/
	public function resendRefundEmailAsync($orderId, $refundId)
	{
		$mozuClient = RefundClient::resendRefundEmailClient($orderId, $refundId);
		$mozuClient = $mozuClient->withContext($this->apiContext);
		return $mozuClient->executeAsync();

	}
	
	
}

?>

