<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\Content;



/**
*	Mozu.Content.Contracts.AddOrDeletePublishItem ApiType DOCUMENT_HERE 
*/
class AddOrDeletePublishItem
{
	/**
	*Mozu.Content.Contracts.AddOrDeletePublishItem docListFQN ApiTypeMember DOCUMENT_HERE 
	*/
	public $docListFQN;

	/**
	*Mozu.Content.Contracts.AddOrDeletePublishItem documentId ApiTypeMember DOCUMENT_HERE 
	*/
	public $documentId;

		public $scopeId;

		public $scopeType;

}

?>
