<?php


/**
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

namespace Mozu\Api\Resources\Commerce\Orders;

use Mozu\Api\MozuClient;
use Mozu\Api\Clients\Commerce\Orders\PackageClient;
use Mozu\Api\ApiContext;

/**
* 
*/
class PackageResource {

	private $apiContext;
	public function __construct(ApiContext $apiContext) 
	{
		$this->apiContext = $apiContext;
	}

	/**
	* 
	*
	* @param string $orderId 
	* @param string $packageId 
	* @return Package 
	*/
	public function getPackage( $orderId,  $packageId, Mozu\Api\Security\AuthTicket &$authTicket= null)
	{
		$mozuClient = PackageClient::getPackageClient( $orderId,  $packageId, $authTicket);
		$mozuClient = $mozuClient->withContext($this->apiContext);
		$mozuClient->execute();
		return $mozuClient->getResult();

	}
	
	/**
	* 
	*
	* @param string $orderId 
	* @param string $packageId 
	* @return array|string 
	*/
	public function getAvailablePackageFulfillmentActions( $orderId,  $packageId, Mozu\Api\Security\AuthTicket &$authTicket= null)
	{
		$mozuClient = PackageClient::getAvailablePackageFulfillmentActionsClient( $orderId,  $packageId, $authTicket);
		$mozuClient = $mozuClient->withContext($this->apiContext);
		$mozuClient->execute();
		return $mozuClient->getResult();

	}
	
	/**
	* 
	*
	* @param string $orderId 
	* @param string $packageId 
	*/
	public function getPackageLabel( $orderId,  $packageId, Mozu\Api\Security\AuthTicket &$authTicket= null)
	{
		$mozuClient = PackageClient::getPackageLabelClient( $orderId,  $packageId, $authTicket);
		$mozuClient = $mozuClient->withContext($this->apiContext);
		$mozuClient->execute();

	}
	
	/**
	* 
	*
	* @param string $orderId 
	* @param Package $package 
	* @return Package 
	*/
	public function createPackage($pkg,  $orderId, Mozu\Api\Security\AuthTicket &$authTicket= null)
	{
		$mozuClient = PackageClient::createPackageClient($pkg,  $orderId, $authTicket);
		$mozuClient = $mozuClient->withContext($this->apiContext);
		$mozuClient->execute();
		return $mozuClient->getResult();

	}
	
	/**
	* 
	*
	* @param string $orderId 
	* @param string $packageId 
	* @param Package $package 
	* @return Package 
	*/
	public function updatePackage($pkg,  $orderId,  $packageId, Mozu\Api\Security\AuthTicket &$authTicket= null)
	{
		$mozuClient = PackageClient::updatePackageClient($pkg,  $orderId,  $packageId, $authTicket);
		$mozuClient = $mozuClient->withContext($this->apiContext);
		$mozuClient->execute();
		return $mozuClient->getResult();

	}
	
	/**
	* 
	*
	* @param string $orderId 
	* @param string $packageId 
	*/
	public function deletePackage( $orderId,  $packageId, Mozu\Api\Security\AuthTicket &$authTicket= null)
	{
		$mozuClient = PackageClient::deletePackageClient( $orderId,  $packageId, $authTicket);
		$mozuClient = $mozuClient->withContext($this->apiContext);
		$mozuClient->execute();

	}
	
	
}

?>

