<?php

/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Urls\Commerce\Catalog\Admin;

use Mozu\Api\MozuUrl;
use Mozu\Api\UrlLocation;

class MasterCatalogUrl  {

	/**
		* Get Resource Url for GetMasterCatalogs
		* @return string Resource Url
	*/
	public static function getMasterCatalogsUrl()
	{
		$url = "/api/commerce/catalog/admin/mastercatalogs/";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"GET", false) ;
		return $mozuUrl;
	}
	
	/**
		* Get Resource Url for GetMasterCatalog
		* @param int $masterCatalogId 
		* @return string Resource Url
	*/
	public static function getMasterCatalogUrl($masterCatalogId)
	{
		$url = "/api/commerce/catalog/admin/mastercatalogs/{masterCatalogId}";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"GET", false) ;
		$url = $mozuUrl->formatUrl("masterCatalogId", $masterCatalogId);
		return $mozuUrl;
	}
	
	/**
		* Get Resource Url for UpdateMasterCatalog
		* @param int $masterCatalogId 
		* @return string Resource Url
	*/
	public static function updateMasterCatalogUrl($masterCatalogId)
	{
		$url = "/api/commerce/catalog/admin/mastercatalogs/{masterCatalogId}";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"PUT", false) ;
		$url = $mozuUrl->formatUrl("masterCatalogId", $masterCatalogId);
		return $mozuUrl;
	}
	
}

?>

