<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\ProductRuntime;



class CategoryImage
{
		public $altText;

		public $cmsId;

		public $imageLabel;

		public $imageUrl;

		public $mediaType;

		public $sequence;

		public $videoUrl;

}

?>
