<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\ProductRuntime;



/**
*	The container for a non-paged list of related site-specific product category properties.
*/
class CategoryCollection
{
	/**
	*The number of the resource entity items listed in the query collection. Signed 64-bit (8-byte) integer. System-supplied and read-only.
	*/
	public $totalCount;

	/**
	*An array list of objects in the returned collection.
	*/
	public $items;

}

?>
