<?php

/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\ProductRuntime;



class ConfiguredProduct
{
		public $productCode;
	public function getProductCode() {
		return $this->productCode;
	}
	
	public function setProductCode($productCode) {
		$this->productCode = $productCode;
		return $this;
	}

		public $variationProductCode;
	public function getVariationProductCode() {
		return $this->variationProductCode;
	}
	
	public function setVariationProductCode($variationProductCode) {
		$this->variationProductCode = $variationProductCode;
		return $this;
	}

		public $availableShippingDiscounts;
	public function getAvailableShippingDiscounts() {
		return $this->availableShippingDiscounts;
	}
	
	public function setAvailableShippingDiscounts($availableShippingDiscounts) {
		$this->availableShippingDiscounts = $availableShippingDiscounts;
		return $this;
	}

		public $inventoryInfo;
	public function getInventoryInfo() {
		return $this->inventoryInfo;
	}
	
	public function setInventoryInfo($inventoryInfo) {
		$this->inventoryInfo = $inventoryInfo;
		return $this;
	}

		public $measurements;
	public function getMeasurements() {
		return $this->measurements;
	}
	
	public function setMeasurements($measurements) {
		$this->measurements = $measurements;
		return $this;
	}

		public $options;
	public function getOptions() {
		return $this->options;
	}
	
	public function setOptions($options) {
		$this->options = $options;
		return $this;
	}

		public $price;
	public function getPrice() {
		return $this->price;
	}
	
	public function setPrice($price) {
		$this->price = $price;
		return $this;
	}

		public $priceRange;
	public function getPriceRange() {
		return $this->priceRange;
	}
	
	public function setPriceRange($priceRange) {
		$this->priceRange = $priceRange;
		return $this;
	}

		public $purchasableState;
	public function getPurchasableState() {
		return $this->purchasableState;
	}
	
	public function setPurchasableState($purchasableState) {
		$this->purchasableState = $purchasableState;
		return $this;
	}

}

?>
