<?php

/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\ProductRuntime;



/**
*	Properties of a message displayed when a product validation failure occurs for a shopper in a storefront.
*/
class ValidationMessage
{
	/**
	*The contents of the message displayed to the user when the product validation failure occurs.
	*/
	public $Message;
	public function getMessage() {
		return $this->Message;
	}
	
	public function setMessage($message) {
		$this->Message = $message;
		return $this;
	}

	/**
	*The severity level of the product validation failure.
	*/
	public $Severity;
	public function getSeverity() {
		return $this->Severity;
	}
	
	public function setSeverity($severity) {
		$this->Severity = $severity;
		return $this;
	}

	/**
	*The entity that triggered the product validation.
	*/
	public $Source;
	public function getSource() {
		return $this->Source;
	}
	
	public function setSource($source) {
		$this->Source = $source;
		return $this;
	}

	/**
	*Unique identifier of the entity that triggered the validation.
	*/
	public $SourceId;
	public function getSourceId() {
		return $this->SourceId;
	}
	
	public function setSourceId($sourceId) {
		$this->SourceId = $sourceId;
		return $this;
	}

}

?>
