<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\CommerceRuntime\Discounts;



/**
*	Properties of a discount defined for a product, order, or shipping on a web storefront.
*/
class Discount
{
		public $expirationDate;

		public $hasMultipleTargetProducts;

		public $id;

		public $itemIds;

		public $name;

}

?>
