<?php


/**
* <auto-generated>
*     This code was generated by Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

namespace Mozu\Api\Clients\Commerce;

use Mozu\Api\MozuClient;
use Mozu\Api\Urls\Commerce\QuoteUrl;


/**
* 
*/
class QuoteClient {

	/**
	* 
	*
	* @param string $filter 
	* @param int $pageSize 
	* @param string $q 
	* @param int $qLimit 
	* @param string $responseFields 
	* @param string $sortBy 
	* @param int $startIndex 
	* @return MozuClient
	*/
	public static function getQuotesClient($startIndex =  null, $pageSize =  null, $sortBy =  null, $filter =  null, $q =  null, $qLimit =  null, $responseFields =  null)
	{
		$url = QuoteUrl::getQuotesUrl($filter, $pageSize, $q, $qLimit, $responseFields, $sortBy, $startIndex);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url);
		return $mozuClient;

	}
	
	/**
	* 
	*
	* @param string $quoteId 
	* @param string $responseFields 
	* @return MozuClient
	*/
	public static function getQuoteClient($quoteId, $responseFields =  null)
	{
		$url = QuoteUrl::getQuoteUrl($quoteId, $responseFields);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url);
		return $mozuClient;

	}
	
	/**
	* 
	*
	* @param int $customerAccountId 
	* @param string $quoteName 
	* @param string $responseFields 
	* @return MozuClient
	*/
	public static function getQuoteByNameClient($customerAccountId, $quoteName, $responseFields =  null)
	{
		$url = QuoteUrl::getQuoteByNameUrl($customerAccountId, $quoteName, $responseFields);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url);
		return $mozuClient;

	}
	
	/**
	* 
	*
	* @param string $responseFields 
	* @param Quote $quote 
	* @return MozuClient
	*/
	public static function createQuoteClient($quote, $responseFields =  null)
	{
		$url = QuoteUrl::createQuoteUrl($responseFields);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url)->withBody($quote);
		return $mozuClient;

	}
	
	/**
	* 
	*
	* @param string $quoteId 
	* @param string $responseFields 
	* @param Quote $quote 
	* @return MozuClient
	*/
	public static function updateQuoteClient($quote, $quoteId, $responseFields =  null)
	{
		$url = QuoteUrl::updateQuoteUrl($quoteId, $responseFields);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url)->withBody($quote);
		return $mozuClient;

	}
	
	/**
	* 
	*
	* @param string $quoteId 
	* @return MozuClient
	*/
	public static function deleteQuoteClient($quoteId)
	{
		$url = QuoteUrl::deleteQuoteUrl($quoteId);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url);
		return $mozuClient;

	}
	
	
}

?>

