<?php


/**
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

namespace Mozu\Api\Clients\Content;

use Mozu\Api\MozuClient;
use Mozu\Api\Urls\Content\DocumentListUrl;

/**
* Use the document lists resource to organize your site's documents into a hierarchy. Document lists can contain documents, folders, and complete hierarchies of folders, which contain documents with unique names.
*/
class DocumentListClient {

	/**
	* Retrieves a collection of document lists.
	*
	* @param long $pageSize Specifies the number of results to display on each page when creating paged results from a query. The maximum value is 200.
	* @param string $sort 
	* @param long $startIndex 
	* @return MozuClient
	*/
	public static function getDocumentListsClient($pageSize, $sort, $startIndex)
	{
		$url = DocumentListUrl::getDocumentListsUrl($pageSize, $sort, $startIndex);
		$verb = "GET";
		$mozuClient = new MozuClient();
		$mozuClient->withVerb($verb)
				->withResourceUrl($url);
		return $mozuClient;

	}
	
	/**
	* Retrieve the details of a document list by providing the list name.
	*
	* @param string $documentListName The name of the document list.
	* @return MozuClient
	*/
	public static function getDocumentListClient($documentListName)
	{
		$url = DocumentListUrl::getDocumentListUrl($documentListName);
		$verb = "GET";
		$mozuClient = new MozuClient();
		$mozuClient->withVerb($verb)
				->withResourceUrl($url);
		return $mozuClient;

	}
	
	
}

?>

