<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\ProductRuntime;



class CurrencyExchangeRate
{
		public $decimalPlaces;

		public $fromCurrencyCode;

		public $multiplier;

		public $rate;

		public $referenceData;

		public $roundingStrategy;

		public $toCurrencyCode;

}

?>
