<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\ProductRuntime;



/**
*	Properties of the active product inventory levels for a specific location.
*/
class LocationInventory
{
		public $locationCode;

		public $productCode;

		public $softStockAvailable;

		public $stockAvailable;

}

?>
