<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\ProductRuntime;



/**
*	Properties of the active inventory managed for the product.
*/
class ProductInventoryInfo
{
		public $availableDate;

		public $manageStock;

	/**
	*The location code for the direct ship location associated with the available online stock.
	*/
	public $onlineLocationCode;

		public $onlineSoftStockAvailable;

		public $onlineStockAvailable;

		public $outOfStockBehavior;

}

?>
