<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Urls\Content\Documentlists;

use Mozu\Api\MozuUrl;
use Mozu\Api\UrlLocation;

class DocumentUrl  {

	/**
		* Get Resource Url for GetDocument
		* @param string $documentId Identifier of the document being retrieved.
		* @param string $documentListName The name of the document list associated with the document to retrieve.
		* @return string Resource Url
	*/
	public static function getDocumentUrl($documentId, $documentListName)
	{
		$url = "/api/content/documentlists/{documentListName}/documents/{documentId}";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"GET", false) ;
		$url = $mozuUrl->formatUrl("documentId", $documentId);
		$url = $mozuUrl->formatUrl("documentListName", $documentListName);
		return $mozuUrl;
	}
	
	/**
		* Get Resource Url for GetDocumentContent
		* @param string $documentId Unique identifier of the document.
		* @param string $documentListName The name of the document list associated with the document.
		* @return string Resource Url
	*/
	public static function getDocumentContentUrl($documentId, $documentListName)
	{
		$url = "/api/content/documentlists/{documentListName}/documents/{documentId}/content";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"GET", false) ;
		$url = $mozuUrl->formatUrl("documentId", $documentId);
		$url = $mozuUrl->formatUrl("documentListName", $documentListName);
		return $mozuUrl;
	}
	
	/**
		* Get Resource Url for GetDocuments
		* @param string $documentListName The name of the document list.
		* @param string $filter A set of expressions that consist of a field, operator, and value and represent search parameter syntax when filtering results of a query. You can filter a document's search results by any of its properties, including its name or folder path. Valid operators include equals (eq), does not equal (ne), greater than (gt), less than (lt), greater than or equal to (ge), less than or equal to (le), starts with (sw), or contains (cont). For example - "filter=Name+sw+Events"
		* @param int $pageSize The number of results to display on each page when creating paged results from a query. The maximum value is 200.
		* @param string $sortBy The property by which to sort results and whether the results appear in ascending (a-z) order, represented by ASC or in descending (z-a) order, represented by DESC. The sortBy parameter follows an available property. For example: "sortBy=productCode+asc"
		* @param int $startIndex When creating paged results from a query, this value indicates the zero-based offset in the complete result set where the returned entities begin. For example, with a PageSize of 25, to get the 51st through the 75th items, use startIndex=3.
		* @return string Resource Url
	*/
	public static function getDocumentsUrl($documentListName, $filter, $pageSize, $sortBy, $startIndex)
	{
		$url = "/api/content/documentlists/{documentListName}/documents?filter={filter}&sortBy={sortBy}&pageSize={pageSize}&startIndex={startIndex}";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"GET", false) ;
		$url = $mozuUrl->formatUrl("documentListName", $documentListName);
		$url = $mozuUrl->formatUrl("filter", $filter);
		$url = $mozuUrl->formatUrl("pageSize", $pageSize);
		$url = $mozuUrl->formatUrl("sortBy", $sortBy);
		$url = $mozuUrl->formatUrl("startIndex", $startIndex);
		return $mozuUrl;
	}
	
	/**
		* Get Resource Url for CreateDocument
		* @param string $documentListName The descriptive alphanumeric document list name being created.
		* @return string Resource Url
	*/
	public static function createDocumentUrl($documentListName)
	{
		$url = "/api/content/documentlists/{documentListName}/documents";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"POST", false) ;
		$url = $mozuUrl->formatUrl("documentListName", $documentListName);
		return $mozuUrl;
	}
	
	/**
		* Get Resource Url for UpdateDocument
		* @param string $documentId Unique identifier of the document to update.
		* @param string $documentListName Name of the document list associated with the document.
		* @return string Resource Url
	*/
	public static function updateDocumentUrl($documentId, $documentListName)
	{
		$url = "/api/content/documentlists/{documentListName}/documents/{documentId}";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"PUT", false) ;
		$url = $mozuUrl->formatUrl("documentId", $documentId);
		$url = $mozuUrl->formatUrl("documentListName", $documentListName);
		return $mozuUrl;
	}
	
	/**
		* Get Resource Url for UpdateDocumentContent
		* @param string $documentId Unique identifier of the document.
		* @param string $documentListName The name of the document list associated with the document.
		* @return string Resource Url
	*/
	public static function updateDocumentContentUrl($documentId, $documentListName)
	{
		$url = "/api/content/documentlists/{documentListName}/documents/{documentId}/content";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"PUT", false) ;
		$url = $mozuUrl->formatUrl("documentId", $documentId);
		$url = $mozuUrl->formatUrl("documentListName", $documentListName);
		return $mozuUrl;
	}
	
	/**
		* Get Resource Url for DeleteDocument
		* @param string $documentId Identifier of the document being deleted.
		* @param string $documentListName The name of the document list associated with the document list being deleted.
		* @return string Resource Url
	*/
	public static function deleteDocumentUrl($documentId, $documentListName)
	{
		$url = "/api/content/documentlists/{documentListName}/documents/{documentId}";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"DELETE", false) ;
		$url = $mozuUrl->formatUrl("documentId", $documentId);
		$url = $mozuUrl->formatUrl("documentListName", $documentListName);
		return $mozuUrl;
	}
	
	/**
		* Get Resource Url for DeleteDocumentContent
		* @param string $documentId Unique identifier of the document.
		* @param string $documentListName The name of the document list associated with the document.
		* @return string Resource Url
	*/
	public static function deleteDocumentContentUrl($documentId, $documentListName)
	{
		$url = "/api/content/documentlists/{documentListName}/documents/{documentId}/content";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"DELETE", false) ;
		$url = $mozuUrl->formatUrl("documentId", $documentId);
		$url = $mozuUrl->formatUrl("documentListName", $documentListName);
		return $mozuUrl;
	}
	
}

?>

