<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\ProductRuntime;



/**
*	Properties of a message displayed when a product validation failure occurs for a shopper in a storefront.
*/
class ValidationMessage
{
	/**
	*The contents of the message displayed to the user when the product validation failure occurs.
	*/
	public $message;

	/**
	*The severity level of the product validation failure.
	*/
	public $severity;

	/**
	*The entity that triggered the product validation.
	*/
	public $source;

	/**
	*Unique identifier of the entity that triggered the validation.
	*/
	public $sourceId;

		public $validationType;

}

?>
