<?php


/**
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

namespace Mozu\Api\Clients\Commerce\Customer\Accounts;

use Mozu\Api\MozuClient;
use Mozu\Api\Urls\Commerce\Customer\Accounts\CustomerGroupUrl;

/**
* 
*/
class CustomerGroupClient {

	/**
	* 
	*
	* @param int $accountId 
	* @param string $filter 
	* @param int $pageSize 
	* @param string $sortBy 
	* @param int $startIndex 
	* @return MozuClient
	*/
	public static function getAccountGroupsClient( $accountId, $filter =  null, $pageSize =  null, $sortBy =  null, $startIndex =  null, Mozu\Api\Security\AuthTicket &$authTicket= null)
	{
		$url = CustomerGroupUrl::getAccountGroupsUrl($accountId, $filter, $pageSize, $sortBy, $startIndex);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url);
		if ($authTicket != null)
			$mozuClient = $mozuClient->withUserAuth($authTicket);
		return $mozuClient;

	}
	
	/**
	* 
	*
	* @param int $accountId 
	* @param int $groupId 
	* @return MozuClient
	*/
	public static function getAccountGroupClient( $accountId,  $groupId, Mozu\Api\Security\AuthTicket &$authTicket= null)
	{
		$url = CustomerGroupUrl::getAccountGroupUrl($accountId, $groupId);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url);
		if ($authTicket != null)
			$mozuClient = $mozuClient->withUserAuth($authTicket);
		return $mozuClient;

	}
	
	/**
	* 
	*
	* @param int $accountId 
	* @param int $groupId 
	* @return MozuClient
	*/
	public static function addAccountGroupClient( $accountId,  $groupId, Mozu\Api\Security\AuthTicket &$authTicket= null)
	{
		$url = CustomerGroupUrl::addAccountGroupUrl($accountId, $groupId);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url);
		if ($authTicket != null)
			$mozuClient = $mozuClient->withUserAuth($authTicket);
		return $mozuClient;

	}
	
	/**
	* 
	*
	* @param int $accountId 
	* @param int $groupId 
	*/
	public static function deleteAccountGroupClient( $accountId,  $groupId, Mozu\Api\Security\AuthTicket &$authTicket= null)
	{
		$url = CustomerGroupUrl::deleteAccountGroupUrl($accountId, $groupId);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url);
		if ($authTicket != null)
			$mozuClient = $mozuClient->withUserAuth($authTicket);
		return $mozuClient;

	}
	
	
}

?>

