<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Urls\Commerce\Shipping\Admin\Profiles;

use Mozu\Api\MozuUrl;
use Mozu\Api\UrlLocation;

class OrderHandlingFeeRulesUrl  {

	/**
		* Get Resource Url for GetOrderHandlingFeeRule
		* @param string $id 
		* @param string $profilecode 
		* @param string $responseFields 
		* @return string Resource Url
	*/
	public static function getOrderHandlingFeeRuleUrl($id, $profilecode, $responseFields)
	{
		$url = "/api/commerce/shipping/admin/profiles/{profilecode}/rules/orderhandlingfees/{id}?responseFields={responseFields}";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"GET", false) ;
		$url = $mozuUrl->formatUrl("id", $id);
		$url = $mozuUrl->formatUrl("profilecode", $profilecode);
		$url = $mozuUrl->formatUrl("responseFields", $responseFields);
		return $mozuUrl;
	}
	
	/**
		* Get Resource Url for GetOrderHandlingFeeRules
		* @param string $profilecode 
		* @param string $responseFields 
		* @return string Resource Url
	*/
	public static function getOrderHandlingFeeRulesUrl($profilecode, $responseFields)
	{
		$url = "/api/commerce/shipping/admin/profiles/{profilecode}/rules/orderhandlingfees?responseFields={responseFields}";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"GET", false) ;
		$url = $mozuUrl->formatUrl("profilecode", $profilecode);
		$url = $mozuUrl->formatUrl("responseFields", $responseFields);
		return $mozuUrl;
	}
	
	/**
		* Get Resource Url for CreateOrderHandlingFeeRule
		* @param string $profilecode 
		* @param string $responseFields 
		* @return string Resource Url
	*/
	public static function createOrderHandlingFeeRuleUrl($profilecode, $responseFields)
	{
		$url = "/api/commerce/shipping/admin/profiles/{profilecode}/rules/orderhandlingfees?responseFields={responseFields}";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"POST", false) ;
		$url = $mozuUrl->formatUrl("profilecode", $profilecode);
		$url = $mozuUrl->formatUrl("responseFields", $responseFields);
		return $mozuUrl;
	}
	
	/**
		* Get Resource Url for UpdateOrderHandlingFeeRule
		* @param string $id 
		* @param string $profilecode 
		* @param string $responseFields 
		* @return string Resource Url
	*/
	public static function updateOrderHandlingFeeRuleUrl($id, $profilecode, $responseFields)
	{
		$url = "/api/commerce/shipping/admin/profiles/{profilecode}/rules/orderhandlingfees/{id}?responseFields={responseFields}";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"PUT", false) ;
		$url = $mozuUrl->formatUrl("id", $id);
		$url = $mozuUrl->formatUrl("profilecode", $profilecode);
		$url = $mozuUrl->formatUrl("responseFields", $responseFields);
		return $mozuUrl;
	}
	
	/**
		* Get Resource Url for DeleteOrderHandlingFeeRule
		* @param string $id 
		* @param string $profilecode 
		* @return string Resource Url
	*/
	public static function deleteOrderHandlingFeeRuleUrl($id, $profilecode)
	{
		$url = "/api/commerce/shipping/admin/profiles/{profilecode}/rules/orderhandlingfees/{id}";
		$mozuUrl = new MozuUrl($url, UrlLocation::TENANT_POD,"DELETE", false) ;
		$url = $mozuUrl->formatUrl("id", $id);
		$url = $mozuUrl->formatUrl("profilecode", $profilecode);
		return $mozuUrl;
	}
	
}

?>

