<?php

/*
* <auto-generated>
*     This code was generated by a tool.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\ShippingAdmin;



/**
*	Properties of a carrier configured in the shipping admin.
*/
class CarrierConfiguration
{
	/**
	*Identifier of the carrier configuration.
	*/
	public $Id;
	public function getId() {
		return $this->Id;
	}
	
	public function setId($id) {
		$this->Id = $id;
		return $this;
	}

	/**
	*Identifier and datetime stamp information recorded when creating or updating a resource entity. This value is system-supplied and read-only.
	*/
	public $AuditInfo;
	public function getAuditInfo() {
		return $this->AuditInfo;
	}
	
	public function setAuditInfo($auditInfo) {
		$this->AuditInfo = $auditInfo;
		return $this;
	}

	/**
	*List of shipping carrier service types configured in the shipping admin. For example, in the request body, the service types have a code, localized content, and several other parameters to add information about a service type.
	*/
	public $ConfiguredServiceTypes;
	public function getConfiguredServiceTypes() {
		return $this->ConfiguredServiceTypes;
	}
	
	public function setConfiguredServiceTypes($configuredServiceTypes) {
		$this->ConfiguredServiceTypes = $configuredServiceTypes;
		return $this;
	}

	/**
	*Wrapper for a group of properties such as a label that includes a value and a locale code, audit information, and a key-value pair.
	*/
	public $Settings;
	public function getSettings() {
		return $this->Settings;
	}
	
	public function setSettings($settings) {
		$this->Settings = $settings;
		return $this;
	}

}

?>
