<?php

/*
* <auto-generated>
*     This code was generated by a Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/


namespace Mozu\Api\Contracts\SiteSettings\General;



/**
*	Mozu.SiteSettings.General.Contracts.EmailTypeSetting ApiType DOCUMENT_HERE 
*/
class EmailTypeSetting
{
	/**
	*Email Address used to bcc in emails
	*/
	public $bccEmailAddressOverride;

	/**
	*Unique identifier of the source product property. For a product field it will be the name of the field. For a product attribute it will be the Attribute FQN. 
	*/
	public $id;

	/**
	*Email address to display on email messages sent from your site.
	*/
	public $replyToEmailAddressOverride;

	/**
	*Email address used in emails sent to your shoppers
	*/
	public $senderEmailAddressOverride;

	/**
	*Email Alais used in emails sent to your shoppers
	*/
	public $senderEmailAliasOverride;

}

?>
