<?php


/**
* <auto-generated>
*     This code was generated by Codezu.     
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
* </auto-generated>
*/

namespace Mozu\Api\Clients\Commerce\Catalog\Admin;

use Mozu\Api\MozuClient;
use Mozu\Api\Urls\Commerce\Catalog\Admin\PriceListUrl;


/**
* Allows you to create and manage products that you will offer on your storefront. You can create products with options that a shopper configures (such as a T-shirt color and size). You can set discounts and sale prices for your products, manage product inventory, and more.
*/
class PriceListClient {

	/**
	* admin-pricelists Get GetPriceLists description DOCUMENT_HERE 
	*
	* @param string $filter A set of filter expressions representing the search parameters for a query. This parameter is optional. Refer to [Sorting and Filtering](../../../../Developer/applications/sorting-filtering.htm) for a list of supported filters.
	* @param int $pageSize When creating paged results from a query, this value indicates the zero-based offset in the complete result set where the returned entities begin. For example, with this parameter set to 25, to get the 51st through the 75th items, set startIndex to 50.
	* @param string $responseFields Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.
	* @param string $sortBy The element to sort the results by and the channel in which the results appear. Either ascending (a-z) or descending (z-a) channel. Optional. Refer to [Sorting and Filtering](../../../../Developer/applications/sorting-filtering.htm) for more information.
	* @param int $startIndex When creating paged results from a query, this value indicates the zero-based offset in the complete result set where the returned entities begin. For example, with pageSize set to 25, to get the 51st through the 75th items, set this parameter to 50.
	* @return MozuClient
	*/
	public static function getPriceListsClient($startIndex =  null, $pageSize =  null, $sortBy =  null, $filter =  null, $responseFields =  null)
	{
		$url = PriceListUrl::getPriceListsUrl($filter, $pageSize, $responseFields, $sortBy, $startIndex);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url);
		return $mozuClient;

	}
	
	/**
	* admin-pricelists Get GetPriceList description DOCUMENT_HERE 
	*
	* @param string $priceListCode The unique, user-defined code of the price list.
	* @param string $responseFields Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.
	* @return MozuClient
	*/
	public static function getPriceListClient($priceListCode, $responseFields =  null)
	{
		$url = PriceListUrl::getPriceListUrl($priceListCode, $responseFields);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url);
		return $mozuClient;

	}
	
	/**
	* admin-pricelists Post AddPriceList description DOCUMENT_HERE 
	*
	* @param string $responseFields Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.
	* @param PriceList $priceList Mozu.ProductAdmin.Contracts.PriceList ApiType DOCUMENT_HERE 
	* @return MozuClient
	*/
	public static function addPriceListClient($priceList, $responseFields =  null)
	{
		$url = PriceListUrl::addPriceListUrl($responseFields);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url)->withBody($priceList);
		return $mozuClient;

	}
	
	/**
	* admin-pricelists Put UpdatePriceList description DOCUMENT_HERE 
	*
	* @param string $priceListCode The unique, user-defined code of the price list.
	* @param string $responseFields Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.
	* @param PriceList $priceList Mozu.ProductAdmin.Contracts.PriceList ApiType DOCUMENT_HERE 
	* @return MozuClient
	*/
	public static function updatePriceListClient($priceList, $priceListCode, $responseFields =  null)
	{
		$url = PriceListUrl::updatePriceListUrl($priceListCode, $responseFields);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url)->withBody($priceList);
		return $mozuClient;

	}
	
	/**
	* admin-pricelists Delete DeletePriceList description DOCUMENT_HERE 
	*
	* @param bool $cascadeDeleteEntries Specifies whether to deletes all price list entries associated with the price list.
	* @param string $priceListCode The unique, user-defined code of the price list.
	*/
	public static function deletePriceListClient($priceListCode, $cascadeDeleteEntries =  null)
	{
		$url = PriceListUrl::deletePriceListUrl($cascadeDeleteEntries, $priceListCode);
		$mozuClient = new MozuClient();
		$mozuClient->withResourceUrl($url);
		return $mozuClient;

	}
	
	
}

?>

